// Automatically generated by syz-sysgen; DO NOT EDIT.

package sys

import (
	"embed"

	"github.com/google/syzkaller/sys/generated"

	"github.com/google/syzkaller/sys/darwin"
	"github.com/google/syzkaller/sys/freebsd"
	"github.com/google/syzkaller/sys/fuchsia"
	"github.com/google/syzkaller/sys/linux"
	"github.com/google/syzkaller/sys/netbsd"
	"github.com/google/syzkaller/sys/openbsd"
	"github.com/google/syzkaller/sys/test"
	"github.com/google/syzkaller/sys/trusty"
	"github.com/google/syzkaller/sys/windows"
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	generated.Register("darwin", "amd64", "872bba2ae5409477b673378e8bd7f3c4cb76fb57", darwin.InitTarget, files)
	generated.Register("freebsd", "386", "998df1771bdbed95c1e813657f0303c22863bda9", freebsd.InitTarget, files)
	generated.Register("freebsd", "amd64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "arm64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "riscv64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("fuchsia", "amd64", "964c7fd4b1c8b2f056ea0047c6f157b808eace6d", fuchsia.InitTarget, files)
	generated.Register("fuchsia", "arm64", "aabea56d7a220b467494a72b09e415bcfe2e82a0", fuchsia.InitTarget, files)
	generated.Register("linux", "386", "f1558906b3ee1e591b565b057e744cf81a0da94c", linux.InitTarget, files)
	generated.Register("linux", "amd64", "6ba67b53a7ad5f1617f4ca8abc93e9f53ed5540d", linux.InitTarget, files)
	generated.Register("linux", "arm", "275107dddb10f68386f3e005058640ee568f25b7", linux.InitTarget, files)
	generated.Register("linux", "arm64", "d6ac540d2a89dbe2bd379103ec1bd3955bc6ed56", linux.InitTarget, files)
	generated.Register("linux", "mips64le", "50dc91c0924a78c8852879576947e8f2f63e789b", linux.InitTarget, files)
	generated.Register("linux", "ppc64le", "bc3d6f47ee5d056ccfdaa6816502ecc77bc21809", linux.InitTarget, files)
	generated.Register("linux", "riscv64", "afc7631e82560afda75dd30ea0f4883268474cac", linux.InitTarget, files)
	generated.Register("linux", "s390x", "2b4350f51c4836a898944fc0b5cec3470b662967", linux.InitTarget, files)
	generated.Register("netbsd", "amd64", "e55c41320cbb764d170d09a2ed5dbe024471a081", netbsd.InitTarget, files)
	generated.Register("openbsd", "amd64", "1ea000ab9607526f7e5426a3893355348153b581", openbsd.InitTarget, files)
	generated.Register("test", "32", "48599de230b91d089940980991402ab1783c69ba", test.InitTarget, files)
	generated.Register("test", "32_fork", "1058db8066db1b5bf2660ed42c5a62a222773757", test.InitTarget, files)
	generated.Register("test", "64", "7fc6301f9f7117123d73c58034e0450720941850", test.InitTarget, files)
	generated.Register("test", "64_fork", "ec185e995c1a76336ca716986b0a43c9da189b85", test.InitTarget, files)
	generated.Register("test", "64_fuzz", "ad8839583df7fb53c0f52d5f55bd445f449a2a34", test.InitTarget, files)
	generated.Register("trusty", "arm", "e15883cf9bc294d71c2d4e06d02c4bda0414a94f", trusty.InitTarget, files)
	generated.Register("windows", "amd64", "f14e4fef7483fea72b1b0867de524882897680c6", windows.InitTarget, files)

}
