// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include <linux/futex.h>
#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void thread_start(void* (*fn)(void*), void* arg)
{
  pthread_t th;
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, 128 << 10);
  int i = 0;
  for (; i < 100; i++) {
    if (pthread_create(&th, &attr, fn, arg) == 0) {
      pthread_attr_destroy(&attr);
      return;
    }
    if (errno == EAGAIN) {
      usleep(50);
      continue;
    }
    break;
  }
  exit(1);
}

typedef struct {
  int state;
} event_t;

static void event_init(event_t* ev)
{
  ev->state = 0;
}

static void event_reset(event_t* ev)
{
  ev->state = 0;
}

static void event_set(event_t* ev)
{
  if (ev->state)
    exit(1);
  __atomic_store_n(&ev->state, 1, __ATOMIC_RELEASE);
  syscall(SYS_futex, &ev->state, FUTEX_WAKE | FUTEX_PRIVATE_FLAG, 1000000);
}

static void event_wait(event_t* ev)
{
  while (!__atomic_load_n(&ev->state, __ATOMIC_ACQUIRE))
    syscall(SYS_futex, &ev->state, FUTEX_WAIT | FUTEX_PRIVATE_FLAG, 0, 0);
}

static int event_isset(event_t* ev)
{
  return __atomic_load_n(&ev->state, __ATOMIC_ACQUIRE);
}

static int event_timedwait(event_t* ev, uint64_t timeout)
{
  uint64_t start = current_time_ms();
  uint64_t now = start;
  for (;;) {
    uint64_t remain = timeout - (now - start);
    struct timespec ts;
    ts.tv_sec = remain / 1000;
    ts.tv_nsec = (remain % 1000) * 1000 * 1000;
    syscall(SYS_futex, &ev->state, FUTEX_WAIT | FUTEX_PRIVATE_FLAG, 0, &ts);
    if (__atomic_load_n(&ev->state, __ATOMIC_ACQUIRE))
      return 1;
    now = current_time_ms();
    if (now - start > timeout)
      return 0;
  }
}

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static inline long write_sysctl(const char* path, long value)
{
  int fd = open(path, O_WRONLY);
  if (fd < 0)
    return -errno;
  char buf[64];
  int n = snprintf(buf, sizeof(buf), "%ld", value);
  if (n < 0) {
    int e = errno;
    close(fd);
    return -e;
  }
  ssize_t w = write(fd, buf, (size_t)n);
  if (w != n) {
    int e = errno;
    close(fd);
    return -e;
  }
  close(fd);
  return 0;
}

struct thread_t {
  int created, call;
  event_t ready, done;
};

static struct thread_t threads[16];
static void execute_call(int call);
static int running;

static void* thr(void* arg)
{
  struct thread_t* th = (struct thread_t*)arg;
  for (;;) {
    event_wait(&th->ready);
    event_reset(&th->ready);
    execute_call(th->call);
    __atomic_fetch_sub(&running, 1, __ATOMIC_RELAXED);
    event_set(&th->done);
  }
  return 0;
}

static void loop(void)
{
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  int i, call, thread;
  for (call = 0; call < 2; call++) {
    for (thread = 0; thread < (int)(sizeof(threads) / sizeof(threads[0]));
         thread++) {
      struct thread_t* th = &threads[thread];
      if (!th->created) {
        th->created = 1;
        event_init(&th->ready);
        event_init(&th->done);
        event_set(&th->done);
        thread_start(thr, th);
      }
      if (!event_isset(&th->done))
        continue;
      event_reset(&th->done);
      th->call = call;
      __atomic_fetch_add(&running, 1, __ATOMIC_RELAXED);
      event_set(&th->ready);
      if (call == 0)
        break;
      event_timedwait(&th->done, 50 + (call == 0 ? 4000 : 0));
      break;
    }
  }
  for (i = 0; i < 100 && __atomic_load_n(&running, __ATOMIC_RELAXED); i++)
    sleep_ms(1);
}

void execute_call(int call)
{
  switch (call) {
  case 0:
    memcpy((void*)0x200000000200, "ext3\000", 5);
    memcpy((void*)0x200000000000, "./file0\000", 8);
    *(uint8_t*)0x200000000580 = 0;
    memcpy(
        (void*)0x200000000240,
        "\x78\x9c\xec\xdd\x5d\x68\x64\x57\x1d\x00\xf0\xff\x9d\xc9\x6c\xb3\xdd"
        "\xac\x49\xd5\x87\x5a\x68\x5d\xb4\xb2\x5b\x74\x67\x92\xc6\xb6\xc1\x87"
        "\x76\x05\xf1\xad\xa0\xd4\xf7\x35\x24\xb3\x21\xec\x24\x13\x32\x49\xbb"
        "\x09\xc5\xa6\xf8\xe0\x8b\x20\x88\xa8\xe0\x93\x4f\xbe\x08\x3e\xf8\x28"
        "\x48\x9f\x7d\x92\x42\xc1\xbe\x8b\x8a\x22\x76\xab\x0f\x82\x1f\xb7\xdc"
        "\x3b\x77\x92\xc9\xf4\x4e\x92\x6d\x93\x49\x36\xf9\xfd\xe0\xdc\x39\xe7"
        "\x7e\xfd\xcf\x49\xc8\xb9\xf7\xdc\x7b\x73\x27\x80\x0b\xeb\x5a\x44\xdc"
        "\x8a\x88\x6a\x44\x3c\x13\x11\x93\xc5\xfc\x4a\x91\x62\xa7\x9b\xb2\xf5"
        "\xde\xbf\xff\xfa\x42\x96\x92\x48\xd3\x57\xfe\x91\xe4\xdb\x64\xe5\x88"
        "\x48\xfa\xf7\x79\x25\xdb\xa4\xda\xcd\x37\x1e\x29\x8f\xdb\xd9\xda\xbe"
        "\x3b\xdf\x6a\x35\xd7\x8b\x72\x63\x63\x65\xad\xd1\xd9\xda\xbe\xb9\xbc"
        "\x32\xbf\xd4\x5c\x6a\xae\xce\xce\xce\x3c\x3f\xf7\xc2\xdc\x73\x73\xd3"
        "\x87\xb6\x21\x79\xef\xf0\x76\x5e\x8d\x88\x17\xbf\xf6\x97\x1f\xff\xe0"
        "\x17\x5f\x7f\xf1\xb7\x5f\x7a\xed\x8f\xb7\xff\x76\xe3\x3b\x59\xa5\x27"
        "\x8a\xe5\x45\x3b\xfa\xac\x7d\xff\xf0\xbd\x0e\x71\x6b\x2f\xfb\x6e\x3e"
        "\xad\xc5\x78\xdf\xe2\xb1\x88\x58\xff\xc8\x3b\x3f\x5b\xaa\x11\x69\xe4"
        "\x2d\x3c\xc0\xe5\x91\x55\x07\x00\x80\x43\xd4\x23\xe2\x93\x11\xf1\xb9"
        "\xfc\xfc\x7f\x32\xaa\xf9\xd9\x69\xee\xc0\x53\x3a\x00\x00\x00\xe0\xe1"
        "\x91\xbe\x34\x11\xff\x4d\x22\x52\x00\x00\x00\xe0\xdc\x7a\x29\x7f\x06"
        "\x36\xa9\xd4\x8b\xe7\x7d\x27\xa2\x52\xa9\xd7\xbb\xcf\xf0\x7e\x3a\x1e"
        "\xad\xb4\xda\x9d\x8d\x2f\xde\x69\x6f\xae\x2e\x76\x9f\x95\x9d\x8a\x5a"
        "\xe5\xce\x72\xab\x39\x5d\x3c\x2b\x3c\x15\xb5\x24\x2b\xcf\xe4\xf9\xbd"
        "\xf2\xb3\x03\xe5\xd9\x88\x78\x2c\x22\x7e\x34\x79\x39\x2f\xd7\x17\xda"
        "\xad\xc5\xd3\xbe\xf8\x01\x00\x00\x00\x17\xc4\x95\x81\xf1\xff\xbf\x26"
        "\xbb\xe3\xff\x4c\xf5\xa3\xff\x07\x2c\x00\x00\x00\x70\xd6\x4c\x9d\x76"
        "\x05\x00\x00\x00\x80\x13\x37\x6c\xfc\xbf\xfb\x56\xef\x21\x2f\xf1\x06"
        "\x00\x00\x00\x1e\x1e\xbb\xe3\x7f\xe3\x7c\x00\x00\x00\x38\x8f\xbe\xf1"
        "\xf2\xcb\x59\x4a\x7b\xdf\x7f\xbd\xf8\xea\xd6\xe6\xdd\xf6\xab\x37\x17"
        "\x9b\x9d\xbb\xf5\x95\xcd\x85\xfa\x42\x7b\x7d\xad\xbe\xd4\x6e\x2f\xe5"
        "\xef\xec\x5b\x39\x6c\x7f\xad\x76\x7b\xed\xcb\xb1\xba\x79\xaf\xb1\xd1"
        "\xec\x6c\x34\x3a\x5b\xdb\xb7\x57\xda\x9b\xab\x1b\xb7\x97\xf7\x7d\x05"
        "\x36\x00\x00\x00\x30\x42\x8f\x7d\xf6\xad\x77\x93\x88\xd8\xf9\xca\xe5"
        "\x3c\x65\x2e\x65\x93\xea\x90\x0d\xbc\x2b\x00\xce\x8d\xca\x83\xac\xfc"
        "\xe7\x93\xab\x07\x30\x7a\xc3\x0e\xf3\xc0\xf9\x37\xf6\xa0\x1b\xa4\xbb"
        "\x39\x5d\x07\x3c\xec\x76\x4e\xbb\x02\xc0\x69\x4b\xfa\x0b\x25\x27\x05"
        "\xfd\x0f\xef\xec\xbb\x66\xf0\xfb\x93\xab\x13\x00\x00\x70\xbc\xae\x7f"
        "\xa6\xfc\xfe\x7f\x36\x04\xa8\x1d\xb8\xe5\xb5\x11\xd5\x10\x38\x29\x0f"
        "\x74\xff\x1f\x38\x57\xdc\xc4\x83\x8b\xab\xf4\xfe\xff\x7f\xf2\xe9\x74"
        "\xc9\xb9\xc1\xdb\x27\x5e\x21\x60\x64\x6a\xce\x00\xe0\xc2\xeb\xbb\xff"
        "\x9f\x96\x2d\x1f\xfa\xf2\x8e\x23\xdf\xff\x4f\xd3\x43\xf7\x05\x00\x00"
        "\x9c\xa8\x89\x3c\x25\x95\x7a\x71\x2f\x70\x22\x2a\x95\xfa\xb5\x88\xab"
        "\xf9\xbf\xfa\xd7\x92\x3b\xcb\xad\xe6\x74\x44\x7c\x22\x22\xfe\x30\x59"
        "\x7b\x24\x2b\xcf\xe4\x5b\x26\xfb\x9f\x19\x06\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x86\x4a\xd3\x24"
        "\x52\x00\x00\x00\xe0\x5c\x8b\xa8\xfc\x35\x29\xbe\xff\xeb\xfa\xe4\xd3"
        "\x13\x83\xd7\x07\x2e\x25\xff\x9e\xcc\x3f\x23\xe2\xb5\x9f\xbd\x52\xb9"
        "\x37\xbf\xb1\xb1\x3e\x93\xcd\x7f\xaf\x37\xff\x56\x44\xfc\x24\x9f\xff"
        "\xec\x69\x5c\xc1\x00\x00\x00\x00\x06\xf5\xc6\xe9\xbd\x71\x3c\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x1c\xa7\xf7\xef\xbf\xbe\xd0\x4b\xa3\x8c\xfb\xf7\xaf\x46\xc4"
        "\xd4\x6e\xfc\x64\x27\xa2\x88\x3f\x16\xe3\xf9\xe7\x78\xd4\x22\xe2\xd1"
        "\x7f\x26\x31\xd6\xb7\x5d\x12\x11\xd5\x63\x88\xbf\xf3\x66\x44\x3c\xde"
        "\xdf\xfe\x5a\x1e\x3b\x8b\x30\x95\x57\xad\x5b\x8b\xc1\xf8\x95\x88\xb8"
        "\x7c\x22\xf1\x7b\x3f\xff\x6e\xfc\x4b\x31\xfe\x64\x9a\xa6\xa5\xf1\xaf"
        "\x1c\x43\x7c\xb8\xc8\xde\xca\xfa\x9f\x5b\x65\x7f\x7f\x95\xb8\x96\x7f"
        "\x96\xff\xfd\x8f\x15\xe9\xe3\x1a\xe8\xff\xf6\xc5\xef\xf5\x7f\xd5\xc8"
        "\xbb\xc0\x0f\xf5\x7f\x57\x8f\x18\xe3\x89\x77\x7e\xd5\x18\x1a\xff\xcd"
        "\x88\x27\xc6\xca\xfb\x9f\x5e\xfc\x64\xaf\xfd\xbb\x55\x18\xda\xf7\x95"
        "\xfc\x50\xbe\xfd\xad\xed\xed\x61\xab\xa7\x3f\x8f\xb8\x5e\x7a\xfc\x49"
        "\x76\xd7\xc9\x72\x8d\x8d\x95\xb5\x46\x67\x6b\xfb\xe6\xf2\xca\xfc\x52"
        "\x73\xa9\xb9\x3a\x3b\x3b\xf3\xfc\xdc\x0b\x73\xcf\xcd\x4d\x37\xee\x2c"
        "\xb7\x9a\xc5\xb4\x34\xc6\x0f\x9f\xfc\xcd\xff\x07\x66\xfd\x2f\xed\xca"
        "\xdb\x1f\x43\xe2\x4f\x7d\xb8\xfd\xfb\xea\xf4\x74\x96\xa9\xf5\x37\x66"
        "\x30\x4c\x11\xec\x9d\x7b\xf7\x3f\xd5\xcd\xd6\x06\x76\x91\xc7\xbf\xf1"
        "\xf9\xf2\xdf\xff\xe3\x07\xc4\xcf\x8e\x7d\x5f\x28\x8e\x03\xd9\xf2\xeb"
        "\xbd\xfc\x4e\x37\xdf\xef\xa9\x5f\xbe\xfd\x54\x69\xc5\x8a\xf8\x8b\x7b"
        "\xed\xff\x5d\xe9\xef\x7f\xfc\x52\x5e\x1e\x6c\xff\x8d\x61\x3b\x1d\xf0"
        "\xcc\x37\xbf\xfb\xa7\x23\xae\x0a\x00\x8c\x40\x67\x6b\xfb\xee\x7c\xab"
        "\xd5\x5c\xff\x38\x99\xef\x45\xff\x9c\xf4\x8d\xd2\x95\x7f\x9a\xa6\xe9"
        "\x31\xc4\x92\x39\x63\x99\x37\x8e\xba\xf2\xf8\x31\x06\xfd\xf5\xd9\x68"
        "\xfb\xe8\x33\xc5\xa0\x24\x4e\x36\xd6\x71\x5c\xd9\x02\x00\x00\xce\x9a"
        "\xbd\x93\xfe\xd3\xae\x09\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x5c\x5c\x9d\xad\xb4\x7a\xcc\x2f\x0f\x4b\x22\x89\x7d"
        "\x73\x06\x63\xee\x9c\x4e\x53\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        "\x0e\xf4\x41\x00\x00\x00\xff\xff\xe8\x29\xe0\x17",
        1389);
    syz_mount_image(
        /*fs=*/0x200000000200, /*dir=*/0x200000000000,
        /*flags=MS_POSIXACL|MS_RELATIME|MS_NOSUID|MS_NOEXEC*/ 0x21000a,
        /*opts=*/0x200000000580, /*chdir=*/1, /*size=*/0x56d,
        /*img=*/0x200000000240);
    break;
  case 1:
    *(uint32_t*)0x200000000340 = 0;
    syscall(__NR_futex, /*addr=*/0ul, /*op=*/0ul, /*val=*/0, /*timeout=*/0ul,
            /*addr2=*/0x200000000340ul, /*val3=*/0);
    break;
  }
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
