// Copyright 2024 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package vminfo

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"syscall"

	"github.com/google/syzkaller/prog"
	"github.com/google/syzkaller/sys/targets"
)

func (linux) syscallCheck(ctx *checkContext, call *prog.Syscall) string {
	check := linuxSyscallChecks[call.CallName]
	if check == nil {
		check = func(ctx *checkContext, call *prog.Syscall) string {
			// Execute plain syscall (rather than a variation with $) to make test program
			// deduplication effective. However, if the plain syscall does not exist take
			// the first variant for this syscall, this still allows to dedup all variants.
			// This works b/c in syscall test we only check for ENOSYS result.
			name := call.CallName
			if ctx.target.SyscallMap[name] == nil {
				for _, call1 := range ctx.target.Syscalls {
					if name == call1.CallName {
						name = call1.Name
					}
				}
			}
			return ctx.supportedSyscalls([]string{name})
		}
	}
	if reason := check(ctx, call); reason != "" {
		return reason
	}
	return linuxSupportedLSM(ctx, call)
}

func linuxSupportedLSM(ctx *checkContext, call *prog.Syscall) string {
	for _, lsm := range []string{"selinux", "apparmor", "smack"} {
		if !strings.Contains(strings.ToLower(call.Name), lsm) {
			continue
		}
		data, err := ctx.readFile("/sys/kernel/security/lsm")
		if err != nil {
			// Securityfs may not be mounted, but it does not mean that no LSMs are enabled.
			if os.IsNotExist(err) {
				break
			}
			return err.Error()
		}
		if !bytes.Contains(data, []byte(lsm)) {
			return fmt.Sprintf("%v is not enabled", lsm)
		}
	}
	return ""
}

var linuxSyscallChecks = map[string]func(*checkContext, *prog.Syscall) string{
	"openat":                                  supportedOpenat,
	"mount":                                   linuxSupportedMount,
	"socket":                                  linuxSupportedSocket,
	"socketpair":                              linuxSupportedSocket,
	"pkey_alloc":                              linuxPkeysSupported,
	"syz_open_dev":                            linuxSyzOpenDevSupported,
	"syz_open_procfs":                         linuxSyzOpenProcfsSupported,
	"syz_open_pts":                            alwaysSupported,
	"syz_execute_func":                        alwaysSupported,
	"syz_emit_ethernet":                       linuxNetInjectionSupported,
	"syz_extract_tcp_res":                     linuxNetInjectionSupported,
	"syz_usb_connect":                         linuxCheckUSBEmulation,
	"syz_usb_connect_ath9k":                   linuxCheckUSBEmulation,
	"syz_usb_disconnect":                      linuxCheckUSBEmulation,
	"syz_usb_control_io":                      linuxCheckUSBEmulation,
	"syz_usb_ep_write":                        linuxCheckUSBEmulation,
	"syz_usb_ep_read":                         linuxCheckUSBEmulation,
	"syz_kvm_setup_cpu":                       linuxSyzKvmSetupCPUSupported,
	"syz_kvm_vgic_v3_setup":                   linuxSyzSupportedOnArm64,
	"syz_kvm_setup_syzos_vm":                  linuxSyzSupportedOnArm64,
	"syz_kvm_add_vcpu":                        linuxSyzSupportedOnArm64,
	"syz_kvm_assert_syzos_uexit":              linuxSyzSupportedOnArm64,
	"syz_kvm_assert_reg":                      linuxSyzSupportedOnArm64,
	"syz_emit_vhci":                           linuxVhciInjectionSupported,
	"syz_init_net_socket":                     linuxSyzInitNetSocketSupported,
	"syz_genetlink_get_family_id":             linuxSyzGenetlinkGetFamilyIDSupported,
	"syz_mount_image":                         linuxSyzMountImageSupported,
	"syz_read_part_table":                     linuxSyzReadPartTableSupported,
	"syz_io_uring_setup":                      alwaysSupported,
	"syz_io_uring_submit":                     alwaysSupported,
	"syz_io_uring_complete":                   alwaysSupported,
	"syz_memcpy_off":                          alwaysSupported,
	"syz_btf_id_by_name":                      linuxBtfVmlinuxSupported,
	"syz_fuse_handle_req":                     alwaysSupported,
	"syz_80211_inject_frame":                  linuxWifiEmulationSupported,
	"syz_80211_join_ibss":                     linuxWifiEmulationSupported,
	"syz_usbip_server_init":                   linuxSyzUsbIPSupported,
	"syz_clone":                               alwaysSupported,
	"syz_clone3":                              alwaysSupported,
	"syz_pkey_set":                            linuxPkeysSupported,
	"syz_socket_connect_nvme_tcp":             linuxSyzSocketConnectNvmeTCPSupported,
	"syz_pidfd_open":                          alwaysSupported,
	"syz_create_resource":                     alwaysSupported,
	"syz_proc_sys_bus_acpi_drivers_autoprobe": alwaysSupported,

	"syz_proc_sys_generated_0":    alwaysSupported,
	"syz_proc_sys_generated_1":    alwaysSupported,
	"syz_proc_sys_generated_2":    alwaysSupported,
	"syz_proc_sys_generated_3":    alwaysSupported,
	"syz_proc_sys_generated_4":    alwaysSupported,
	"syz_proc_sys_generated_5":    alwaysSupported,
	"syz_proc_sys_generated_6":    alwaysSupported,
	"syz_proc_sys_generated_7":    alwaysSupported,
	"syz_proc_sys_generated_8":    alwaysSupported,
	"syz_proc_sys_generated_9":    alwaysSupported,
	"syz_proc_sys_generated_10":   alwaysSupported,
	"syz_proc_sys_generated_11":   alwaysSupported,
	"syz_proc_sys_generated_12":   alwaysSupported,
	"syz_proc_sys_generated_13":   alwaysSupported,
	"syz_proc_sys_generated_14":   alwaysSupported,
	"syz_proc_sys_generated_15":   alwaysSupported,
	"syz_proc_sys_generated_16":   alwaysSupported,
	"syz_proc_sys_generated_17":   alwaysSupported,
	"syz_proc_sys_generated_18":   alwaysSupported,
	"syz_proc_sys_generated_19":   alwaysSupported,
	"syz_proc_sys_generated_20":   alwaysSupported,
	"syz_proc_sys_generated_21":   alwaysSupported,
	"syz_proc_sys_generated_22":   alwaysSupported,
	"syz_proc_sys_generated_23":   alwaysSupported,
	"syz_proc_sys_generated_24":   alwaysSupported,
	"syz_proc_sys_generated_25":   alwaysSupported,
	"syz_proc_sys_generated_26":   alwaysSupported,
	"syz_proc_sys_generated_27":   alwaysSupported,
	"syz_proc_sys_generated_28":   alwaysSupported,
	"syz_proc_sys_generated_29":   alwaysSupported,
	"syz_proc_sys_generated_30":   alwaysSupported,
	"syz_proc_sys_generated_31":   alwaysSupported,
	"syz_proc_sys_generated_32":   alwaysSupported,
	"syz_proc_sys_generated_33":   alwaysSupported,
	"syz_proc_sys_generated_34":   alwaysSupported,
	"syz_proc_sys_generated_35":   alwaysSupported,
	"syz_proc_sys_generated_36":   alwaysSupported,
	"syz_proc_sys_generated_37":   alwaysSupported,
	"syz_proc_sys_generated_38":   alwaysSupported,
	"syz_proc_sys_generated_39":   alwaysSupported,
	"syz_proc_sys_generated_40":   alwaysSupported,
	"syz_proc_sys_generated_41":   alwaysSupported,
	"syz_proc_sys_generated_42":   alwaysSupported,
	"syz_proc_sys_generated_43":   alwaysSupported,
	"syz_proc_sys_generated_44":   alwaysSupported,
	"syz_proc_sys_generated_45":   alwaysSupported,
	"syz_proc_sys_generated_46":   alwaysSupported,
	"syz_proc_sys_generated_47":   alwaysSupported,
	"syz_proc_sys_generated_48":   alwaysSupported,
	"syz_proc_sys_generated_49":   alwaysSupported,
	"syz_proc_sys_generated_50":   alwaysSupported,
	"syz_proc_sys_generated_51":   alwaysSupported,
	"syz_proc_sys_generated_52":   alwaysSupported,
	"syz_proc_sys_generated_53":   alwaysSupported,
	"syz_proc_sys_generated_54":   alwaysSupported,
	"syz_proc_sys_generated_55":   alwaysSupported,
	"syz_proc_sys_generated_56":   alwaysSupported,
	"syz_proc_sys_generated_57":   alwaysSupported,
	"syz_proc_sys_generated_58":   alwaysSupported,
	"syz_proc_sys_generated_59":   alwaysSupported,
	"syz_proc_sys_generated_60":   alwaysSupported,
	"syz_proc_sys_generated_61":   alwaysSupported,
	"syz_proc_sys_generated_62":   alwaysSupported,
	"syz_proc_sys_generated_63":   alwaysSupported,
	"syz_proc_sys_generated_64":   alwaysSupported,
	"syz_proc_sys_generated_65":   alwaysSupported,
	"syz_proc_sys_generated_66":   alwaysSupported,
	"syz_proc_sys_generated_67":   alwaysSupported,
	"syz_proc_sys_generated_68":   alwaysSupported,
	"syz_proc_sys_generated_69":   alwaysSupported,
	"syz_proc_sys_generated_70":   alwaysSupported,
	"syz_proc_sys_generated_71":   alwaysSupported,
	"syz_proc_sys_generated_72":   alwaysSupported,
	"syz_proc_sys_generated_73":   alwaysSupported,
	"syz_proc_sys_generated_74":   alwaysSupported,
	"syz_proc_sys_generated_75":   alwaysSupported,
	"syz_proc_sys_generated_76":   alwaysSupported,
	"syz_proc_sys_generated_77":   alwaysSupported,
	"syz_proc_sys_generated_78":   alwaysSupported,
	"syz_proc_sys_generated_79":   alwaysSupported,
	"syz_proc_sys_generated_80":   alwaysSupported,
	"syz_proc_sys_generated_81":   alwaysSupported,
	"syz_proc_sys_generated_82":   alwaysSupported,
	"syz_proc_sys_generated_83":   alwaysSupported,
	"syz_proc_sys_generated_84":   alwaysSupported,
	"syz_proc_sys_generated_85":   alwaysSupported,
	"syz_proc_sys_generated_86":   alwaysSupported,
	"syz_proc_sys_generated_87":   alwaysSupported,
	"syz_proc_sys_generated_88":   alwaysSupported,
	"syz_proc_sys_generated_89":   alwaysSupported,
	"syz_proc_sys_generated_90":   alwaysSupported,
	"syz_proc_sys_generated_91":   alwaysSupported,
	"syz_proc_sys_generated_92":   alwaysSupported,
	"syz_proc_sys_generated_93":   alwaysSupported,
	"syz_proc_sys_generated_94":   alwaysSupported,
	"syz_proc_sys_generated_95":   alwaysSupported,
	"syz_proc_sys_generated_96":   alwaysSupported,
	"syz_proc_sys_generated_97":   alwaysSupported,
	"syz_proc_sys_generated_98":   alwaysSupported,
	"syz_proc_sys_generated_99":   alwaysSupported,
	"syz_proc_sys_generated_100":  alwaysSupported,
	"syz_proc_sys_generated_101":  alwaysSupported,
	"syz_proc_sys_generated_102":  alwaysSupported,
	"syz_proc_sys_generated_103":  alwaysSupported,
	"syz_proc_sys_generated_104":  alwaysSupported,
	"syz_proc_sys_generated_105":  alwaysSupported,
	"syz_proc_sys_generated_106":  alwaysSupported,
	"syz_proc_sys_generated_107":  alwaysSupported,
	"syz_proc_sys_generated_108":  alwaysSupported,
	"syz_proc_sys_generated_109":  alwaysSupported,
	"syz_proc_sys_generated_110":  alwaysSupported,
	"syz_proc_sys_generated_111":  alwaysSupported,
	"syz_proc_sys_generated_112":  alwaysSupported,
	"syz_proc_sys_generated_113":  alwaysSupported,
	"syz_proc_sys_generated_114":  alwaysSupported,
	"syz_proc_sys_generated_115":  alwaysSupported,
	"syz_proc_sys_generated_116":  alwaysSupported,
	"syz_proc_sys_generated_117":  alwaysSupported,
	"syz_proc_sys_generated_118":  alwaysSupported,
	"syz_proc_sys_generated_119":  alwaysSupported,
	"syz_proc_sys_generated_120":  alwaysSupported,
	"syz_proc_sys_generated_121":  alwaysSupported,
	"syz_proc_sys_generated_122":  alwaysSupported,
	"syz_proc_sys_generated_123":  alwaysSupported,
	"syz_proc_sys_generated_124":  alwaysSupported,
	"syz_proc_sys_generated_125":  alwaysSupported,
	"syz_proc_sys_generated_126":  alwaysSupported,
	"syz_proc_sys_generated_127":  alwaysSupported,
	"syz_proc_sys_generated_128":  alwaysSupported,
	"syz_proc_sys_generated_129":  alwaysSupported,
	"syz_proc_sys_generated_130":  alwaysSupported,
	"syz_proc_sys_generated_131":  alwaysSupported,
	"syz_proc_sys_generated_132":  alwaysSupported,
	"syz_proc_sys_generated_133":  alwaysSupported,
	"syz_proc_sys_generated_134":  alwaysSupported,
	"syz_proc_sys_generated_135":  alwaysSupported,
	"syz_proc_sys_generated_136":  alwaysSupported,
	"syz_proc_sys_generated_137":  alwaysSupported,
	"syz_proc_sys_generated_138":  alwaysSupported,
	"syz_proc_sys_generated_139":  alwaysSupported,
	"syz_proc_sys_generated_140":  alwaysSupported,
	"syz_proc_sys_generated_141":  alwaysSupported,
	"syz_proc_sys_generated_142":  alwaysSupported,
	"syz_proc_sys_generated_143":  alwaysSupported,
	"syz_proc_sys_generated_144":  alwaysSupported,
	"syz_proc_sys_generated_145":  alwaysSupported,
	"syz_proc_sys_generated_146":  alwaysSupported,
	"syz_proc_sys_generated_147":  alwaysSupported,
	"syz_proc_sys_generated_148":  alwaysSupported,
	"syz_proc_sys_generated_149":  alwaysSupported,
	"syz_proc_sys_generated_150":  alwaysSupported,
	"syz_proc_sys_generated_151":  alwaysSupported,
	"syz_proc_sys_generated_152":  alwaysSupported,
	"syz_proc_sys_generated_153":  alwaysSupported,
	"syz_proc_sys_generated_154":  alwaysSupported,
	"syz_proc_sys_generated_155":  alwaysSupported,
	"syz_proc_sys_generated_156":  alwaysSupported,
	"syz_proc_sys_generated_157":  alwaysSupported,
	"syz_proc_sys_generated_158":  alwaysSupported,
	"syz_proc_sys_generated_159":  alwaysSupported,
	"syz_proc_sys_generated_160":  alwaysSupported,
	"syz_proc_sys_generated_161":  alwaysSupported,
	"syz_proc_sys_generated_162":  alwaysSupported,
	"syz_proc_sys_generated_163":  alwaysSupported,
	"syz_proc_sys_generated_164":  alwaysSupported,
	"syz_proc_sys_generated_165":  alwaysSupported,
	"syz_proc_sys_generated_166":  alwaysSupported,
	"syz_proc_sys_generated_167":  alwaysSupported,
	"syz_proc_sys_generated_168":  alwaysSupported,
	"syz_proc_sys_generated_169":  alwaysSupported,
	"syz_proc_sys_generated_170":  alwaysSupported,
	"syz_proc_sys_generated_171":  alwaysSupported,
	"syz_proc_sys_generated_172":  alwaysSupported,
	"syz_proc_sys_generated_173":  alwaysSupported,
	"syz_proc_sys_generated_174":  alwaysSupported,
	"syz_proc_sys_generated_175":  alwaysSupported,
	"syz_proc_sys_generated_176":  alwaysSupported,
	"syz_proc_sys_generated_177":  alwaysSupported,
	"syz_proc_sys_generated_178":  alwaysSupported,
	"syz_proc_sys_generated_179":  alwaysSupported,
	"syz_proc_sys_generated_180":  alwaysSupported,
	"syz_proc_sys_generated_181":  alwaysSupported,
	"syz_proc_sys_generated_182":  alwaysSupported,
	"syz_proc_sys_generated_183":  alwaysSupported,
	"syz_proc_sys_generated_184":  alwaysSupported,
	"syz_proc_sys_generated_185":  alwaysSupported,
	"syz_proc_sys_generated_186":  alwaysSupported,
	"syz_proc_sys_generated_187":  alwaysSupported,
	"syz_proc_sys_generated_188":  alwaysSupported,
	"syz_proc_sys_generated_189":  alwaysSupported,
	"syz_proc_sys_generated_190":  alwaysSupported,
	"syz_proc_sys_generated_191":  alwaysSupported,
	"syz_proc_sys_generated_192":  alwaysSupported,
	"syz_proc_sys_generated_193":  alwaysSupported,
	"syz_proc_sys_generated_194":  alwaysSupported,
	"syz_proc_sys_generated_195":  alwaysSupported,
	"syz_proc_sys_generated_196":  alwaysSupported,
	"syz_proc_sys_generated_197":  alwaysSupported,
	"syz_proc_sys_generated_198":  alwaysSupported,
	"syz_proc_sys_generated_199":  alwaysSupported,
	"syz_proc_sys_generated_200":  alwaysSupported,
	"syz_proc_sys_generated_201":  alwaysSupported,
	"syz_proc_sys_generated_202":  alwaysSupported,
	"syz_proc_sys_generated_203":  alwaysSupported,
	"syz_proc_sys_generated_204":  alwaysSupported,
	"syz_proc_sys_generated_205":  alwaysSupported,
	"syz_proc_sys_generated_206":  alwaysSupported,
	"syz_proc_sys_generated_207":  alwaysSupported,
	"syz_proc_sys_generated_208":  alwaysSupported,
	"syz_proc_sys_generated_209":  alwaysSupported,
	"syz_proc_sys_generated_210":  alwaysSupported,
	"syz_proc_sys_generated_211":  alwaysSupported,
	"syz_proc_sys_generated_212":  alwaysSupported,
	"syz_proc_sys_generated_213":  alwaysSupported,
	"syz_proc_sys_generated_214":  alwaysSupported,
	"syz_proc_sys_generated_215":  alwaysSupported,
	"syz_proc_sys_generated_216":  alwaysSupported,
	"syz_proc_sys_generated_217":  alwaysSupported,
	"syz_proc_sys_generated_218":  alwaysSupported,
	"syz_proc_sys_generated_219":  alwaysSupported,
	"syz_proc_sys_generated_220":  alwaysSupported,
	"syz_proc_sys_generated_221":  alwaysSupported,
	"syz_proc_sys_generated_222":  alwaysSupported,
	"syz_proc_sys_generated_223":  alwaysSupported,
	"syz_proc_sys_generated_224":  alwaysSupported,
	"syz_proc_sys_generated_225":  alwaysSupported,
	"syz_proc_sys_generated_226":  alwaysSupported,
	"syz_proc_sys_generated_227":  alwaysSupported,
	"syz_proc_sys_generated_228":  alwaysSupported,
	"syz_proc_sys_generated_229":  alwaysSupported,
	"syz_proc_sys_generated_230":  alwaysSupported,
	"syz_proc_sys_generated_231":  alwaysSupported,
	"syz_proc_sys_generated_232":  alwaysSupported,
	"syz_proc_sys_generated_233":  alwaysSupported,
	"syz_proc_sys_generated_234":  alwaysSupported,
	"syz_proc_sys_generated_235":  alwaysSupported,
	"syz_proc_sys_generated_236":  alwaysSupported,
	"syz_proc_sys_generated_237":  alwaysSupported,
	"syz_proc_sys_generated_238":  alwaysSupported,
	"syz_proc_sys_generated_239":  alwaysSupported,
	"syz_proc_sys_generated_240":  alwaysSupported,
	"syz_proc_sys_generated_241":  alwaysSupported,
	"syz_proc_sys_generated_242":  alwaysSupported,
	"syz_proc_sys_generated_243":  alwaysSupported,
	"syz_proc_sys_generated_244":  alwaysSupported,
	"syz_proc_sys_generated_245":  alwaysSupported,
	"syz_proc_sys_generated_246":  alwaysSupported,
	"syz_proc_sys_generated_247":  alwaysSupported,
	"syz_proc_sys_generated_248":  alwaysSupported,
	"syz_proc_sys_generated_249":  alwaysSupported,
	"syz_proc_sys_generated_250":  alwaysSupported,
	"syz_proc_sys_generated_251":  alwaysSupported,
	"syz_proc_sys_generated_252":  alwaysSupported,
	"syz_proc_sys_generated_253":  alwaysSupported,
	"syz_proc_sys_generated_254":  alwaysSupported,
	"syz_proc_sys_generated_255":  alwaysSupported,
	"syz_proc_sys_generated_256":  alwaysSupported,
	"syz_proc_sys_generated_257":  alwaysSupported,
	"syz_proc_sys_generated_258":  alwaysSupported,
	"syz_proc_sys_generated_259":  alwaysSupported,
	"syz_proc_sys_generated_260":  alwaysSupported,
	"syz_proc_sys_generated_261":  alwaysSupported,
	"syz_proc_sys_generated_262":  alwaysSupported,
	"syz_proc_sys_generated_263":  alwaysSupported,
	"syz_proc_sys_generated_264":  alwaysSupported,
	"syz_proc_sys_generated_265":  alwaysSupported,
	"syz_proc_sys_generated_266":  alwaysSupported,
	"syz_proc_sys_generated_267":  alwaysSupported,
	"syz_proc_sys_generated_268":  alwaysSupported,
	"syz_proc_sys_generated_269":  alwaysSupported,
	"syz_proc_sys_generated_270":  alwaysSupported,
	"syz_proc_sys_generated_271":  alwaysSupported,
	"syz_proc_sys_generated_272":  alwaysSupported,
	"syz_proc_sys_generated_273":  alwaysSupported,
	"syz_proc_sys_generated_274":  alwaysSupported,
	"syz_proc_sys_generated_275":  alwaysSupported,
	"syz_proc_sys_generated_276":  alwaysSupported,
	"syz_proc_sys_generated_277":  alwaysSupported,
	"syz_proc_sys_generated_278":  alwaysSupported,
	"syz_proc_sys_generated_279":  alwaysSupported,
	"syz_proc_sys_generated_280":  alwaysSupported,
	"syz_proc_sys_generated_281":  alwaysSupported,
	"syz_proc_sys_generated_282":  alwaysSupported,
	"syz_proc_sys_generated_283":  alwaysSupported,
	"syz_proc_sys_generated_284":  alwaysSupported,
	"syz_proc_sys_generated_285":  alwaysSupported,
	"syz_proc_sys_generated_286":  alwaysSupported,
	"syz_proc_sys_generated_287":  alwaysSupported,
	"syz_proc_sys_generated_288":  alwaysSupported,
	"syz_proc_sys_generated_289":  alwaysSupported,
	"syz_proc_sys_generated_290":  alwaysSupported,
	"syz_proc_sys_generated_291":  alwaysSupported,
	"syz_proc_sys_generated_292":  alwaysSupported,
	"syz_proc_sys_generated_293":  alwaysSupported,
	"syz_proc_sys_generated_294":  alwaysSupported,
	"syz_proc_sys_generated_295":  alwaysSupported,
	"syz_proc_sys_generated_296":  alwaysSupported,
	"syz_proc_sys_generated_297":  alwaysSupported,
	"syz_proc_sys_generated_298":  alwaysSupported,
	"syz_proc_sys_generated_299":  alwaysSupported,
	"syz_proc_sys_generated_300":  alwaysSupported,
	"syz_proc_sys_generated_301":  alwaysSupported,
	"syz_proc_sys_generated_302":  alwaysSupported,
	"syz_proc_sys_generated_303":  alwaysSupported,
	"syz_proc_sys_generated_304":  alwaysSupported,
	"syz_proc_sys_generated_305":  alwaysSupported,
	"syz_proc_sys_generated_306":  alwaysSupported,
	"syz_proc_sys_generated_307":  alwaysSupported,
	"syz_proc_sys_generated_308":  alwaysSupported,
	"syz_proc_sys_generated_309":  alwaysSupported,
	"syz_proc_sys_generated_310":  alwaysSupported,
	"syz_proc_sys_generated_311":  alwaysSupported,
	"syz_proc_sys_generated_312":  alwaysSupported,
	"syz_proc_sys_generated_313":  alwaysSupported,
	"syz_proc_sys_generated_314":  alwaysSupported,
	"syz_proc_sys_generated_315":  alwaysSupported,
	"syz_proc_sys_generated_316":  alwaysSupported,
	"syz_proc_sys_generated_317":  alwaysSupported,
	"syz_proc_sys_generated_318":  alwaysSupported,
	"syz_proc_sys_generated_319":  alwaysSupported,
	"syz_proc_sys_generated_320":  alwaysSupported,
	"syz_proc_sys_generated_321":  alwaysSupported,
	"syz_proc_sys_generated_322":  alwaysSupported,
	"syz_proc_sys_generated_323":  alwaysSupported,
	"syz_proc_sys_generated_324":  alwaysSupported,
	"syz_proc_sys_generated_325":  alwaysSupported,
	"syz_proc_sys_generated_326":  alwaysSupported,
	"syz_proc_sys_generated_327":  alwaysSupported,
	"syz_proc_sys_generated_328":  alwaysSupported,
	"syz_proc_sys_generated_329":  alwaysSupported,
	"syz_proc_sys_generated_330":  alwaysSupported,
	"syz_proc_sys_generated_331":  alwaysSupported,
	"syz_proc_sys_generated_332":  alwaysSupported,
	"syz_proc_sys_generated_333":  alwaysSupported,
	"syz_proc_sys_generated_334":  alwaysSupported,
	"syz_proc_sys_generated_335":  alwaysSupported,
	"syz_proc_sys_generated_336":  alwaysSupported,
	"syz_proc_sys_generated_337":  alwaysSupported,
	"syz_proc_sys_generated_338":  alwaysSupported,
	"syz_proc_sys_generated_339":  alwaysSupported,
	"syz_proc_sys_generated_340":  alwaysSupported,
	"syz_proc_sys_generated_341":  alwaysSupported,
	"syz_proc_sys_generated_342":  alwaysSupported,
	"syz_proc_sys_generated_343":  alwaysSupported,
	"syz_proc_sys_generated_344":  alwaysSupported,
	"syz_proc_sys_generated_345":  alwaysSupported,
	"syz_proc_sys_generated_346":  alwaysSupported,
	"syz_proc_sys_generated_347":  alwaysSupported,
	"syz_proc_sys_generated_348":  alwaysSupported,
	"syz_proc_sys_generated_349":  alwaysSupported,
	"syz_proc_sys_generated_350":  alwaysSupported,
	"syz_proc_sys_generated_351":  alwaysSupported,
	"syz_proc_sys_generated_352":  alwaysSupported,
	"syz_proc_sys_generated_353":  alwaysSupported,
	"syz_proc_sys_generated_354":  alwaysSupported,
	"syz_proc_sys_generated_355":  alwaysSupported,
	"syz_proc_sys_generated_356":  alwaysSupported,
	"syz_proc_sys_generated_357":  alwaysSupported,
	"syz_proc_sys_generated_358":  alwaysSupported,
	"syz_proc_sys_generated_359":  alwaysSupported,
	"syz_proc_sys_generated_360":  alwaysSupported,
	"syz_proc_sys_generated_361":  alwaysSupported,
	"syz_proc_sys_generated_362":  alwaysSupported,
	"syz_proc_sys_generated_363":  alwaysSupported,
	"syz_proc_sys_generated_364":  alwaysSupported,
	"syz_proc_sys_generated_365":  alwaysSupported,
	"syz_proc_sys_generated_366":  alwaysSupported,
	"syz_proc_sys_generated_367":  alwaysSupported,
	"syz_proc_sys_generated_368":  alwaysSupported,
	"syz_proc_sys_generated_369":  alwaysSupported,
	"syz_proc_sys_generated_370":  alwaysSupported,
	"syz_proc_sys_generated_371":  alwaysSupported,
	"syz_proc_sys_generated_372":  alwaysSupported,
	"syz_proc_sys_generated_373":  alwaysSupported,
	"syz_proc_sys_generated_374":  alwaysSupported,
	"syz_proc_sys_generated_375":  alwaysSupported,
	"syz_proc_sys_generated_376":  alwaysSupported,
	"syz_proc_sys_generated_377":  alwaysSupported,
	"syz_proc_sys_generated_378":  alwaysSupported,
	"syz_proc_sys_generated_379":  alwaysSupported,
	"syz_proc_sys_generated_380":  alwaysSupported,
	"syz_proc_sys_generated_381":  alwaysSupported,
	"syz_proc_sys_generated_382":  alwaysSupported,
	"syz_proc_sys_generated_383":  alwaysSupported,
	"syz_proc_sys_generated_384":  alwaysSupported,
	"syz_proc_sys_generated_385":  alwaysSupported,
	"syz_proc_sys_generated_386":  alwaysSupported,
	"syz_proc_sys_generated_387":  alwaysSupported,
	"syz_proc_sys_generated_388":  alwaysSupported,
	"syz_proc_sys_generated_389":  alwaysSupported,
	"syz_proc_sys_generated_390":  alwaysSupported,
	"syz_proc_sys_generated_391":  alwaysSupported,
	"syz_proc_sys_generated_392":  alwaysSupported,
	"syz_proc_sys_generated_393":  alwaysSupported,
	"syz_proc_sys_generated_394":  alwaysSupported,
	"syz_proc_sys_generated_395":  alwaysSupported,
	"syz_proc_sys_generated_396":  alwaysSupported,
	"syz_proc_sys_generated_397":  alwaysSupported,
	"syz_proc_sys_generated_398":  alwaysSupported,
	"syz_proc_sys_generated_399":  alwaysSupported,
	"syz_proc_sys_generated_400":  alwaysSupported,
	"syz_proc_sys_generated_401":  alwaysSupported,
	"syz_proc_sys_generated_402":  alwaysSupported,
	"syz_proc_sys_generated_403":  alwaysSupported,
	"syz_proc_sys_generated_404":  alwaysSupported,
	"syz_proc_sys_generated_405":  alwaysSupported,
	"syz_proc_sys_generated_406":  alwaysSupported,
	"syz_proc_sys_generated_407":  alwaysSupported,
	"syz_proc_sys_generated_408":  alwaysSupported,
	"syz_proc_sys_generated_409":  alwaysSupported,
	"syz_proc_sys_generated_410":  alwaysSupported,
	"syz_proc_sys_generated_411":  alwaysSupported,
	"syz_proc_sys_generated_412":  alwaysSupported,
	"syz_proc_sys_generated_413":  alwaysSupported,
	"syz_proc_sys_generated_414":  alwaysSupported,
	"syz_proc_sys_generated_415":  alwaysSupported,
	"syz_proc_sys_generated_416":  alwaysSupported,
	"syz_proc_sys_generated_417":  alwaysSupported,
	"syz_proc_sys_generated_418":  alwaysSupported,
	"syz_proc_sys_generated_419":  alwaysSupported,
	"syz_proc_sys_generated_420":  alwaysSupported,
	"syz_proc_sys_generated_421":  alwaysSupported,
	"syz_proc_sys_generated_422":  alwaysSupported,
	"syz_proc_sys_generated_423":  alwaysSupported,
	"syz_proc_sys_generated_424":  alwaysSupported,
	"syz_proc_sys_generated_425":  alwaysSupported,
	"syz_proc_sys_generated_426":  alwaysSupported,
	"syz_proc_sys_generated_427":  alwaysSupported,
	"syz_proc_sys_generated_428":  alwaysSupported,
	"syz_proc_sys_generated_429":  alwaysSupported,
	"syz_proc_sys_generated_430":  alwaysSupported,
	"syz_proc_sys_generated_431":  alwaysSupported,
	"syz_proc_sys_generated_432":  alwaysSupported,
	"syz_proc_sys_generated_433":  alwaysSupported,
	"syz_proc_sys_generated_434":  alwaysSupported,
	"syz_proc_sys_generated_435":  alwaysSupported,
	"syz_proc_sys_generated_436":  alwaysSupported,
	"syz_proc_sys_generated_437":  alwaysSupported,
	"syz_proc_sys_generated_438":  alwaysSupported,
	"syz_proc_sys_generated_439":  alwaysSupported,
	"syz_proc_sys_generated_440":  alwaysSupported,
	"syz_proc_sys_generated_441":  alwaysSupported,
	"syz_proc_sys_generated_442":  alwaysSupported,
	"syz_proc_sys_generated_443":  alwaysSupported,
	"syz_proc_sys_generated_444":  alwaysSupported,
	"syz_proc_sys_generated_445":  alwaysSupported,
	"syz_proc_sys_generated_446":  alwaysSupported,
	"syz_proc_sys_generated_447":  alwaysSupported,
	"syz_proc_sys_generated_448":  alwaysSupported,
	"syz_proc_sys_generated_449":  alwaysSupported,
	"syz_proc_sys_generated_450":  alwaysSupported,
	"syz_proc_sys_generated_451":  alwaysSupported,
	"syz_proc_sys_generated_452":  alwaysSupported,
	"syz_proc_sys_generated_453":  alwaysSupported,
	"syz_proc_sys_generated_454":  alwaysSupported,
	"syz_proc_sys_generated_455":  alwaysSupported,
	"syz_proc_sys_generated_456":  alwaysSupported,
	"syz_proc_sys_generated_457":  alwaysSupported,
	"syz_proc_sys_generated_458":  alwaysSupported,
	"syz_proc_sys_generated_459":  alwaysSupported,
	"syz_proc_sys_generated_460":  alwaysSupported,
	"syz_proc_sys_generated_461":  alwaysSupported,
	"syz_proc_sys_generated_462":  alwaysSupported,
	"syz_proc_sys_generated_463":  alwaysSupported,
	"syz_proc_sys_generated_464":  alwaysSupported,
	"syz_proc_sys_generated_465":  alwaysSupported,
	"syz_proc_sys_generated_466":  alwaysSupported,
	"syz_proc_sys_generated_467":  alwaysSupported,
	"syz_proc_sys_generated_468":  alwaysSupported,
	"syz_proc_sys_generated_469":  alwaysSupported,
	"syz_proc_sys_generated_470":  alwaysSupported,
	"syz_proc_sys_generated_471":  alwaysSupported,
	"syz_proc_sys_generated_472":  alwaysSupported,
	"syz_proc_sys_generated_473":  alwaysSupported,
	"syz_proc_sys_generated_474":  alwaysSupported,
	"syz_proc_sys_generated_475":  alwaysSupported,
	"syz_proc_sys_generated_476":  alwaysSupported,
	"syz_proc_sys_generated_477":  alwaysSupported,
	"syz_proc_sys_generated_478":  alwaysSupported,
	"syz_proc_sys_generated_479":  alwaysSupported,
	"syz_proc_sys_generated_480":  alwaysSupported,
	"syz_proc_sys_generated_481":  alwaysSupported,
	"syz_proc_sys_generated_482":  alwaysSupported,
	"syz_proc_sys_generated_483":  alwaysSupported,
	"syz_proc_sys_generated_484":  alwaysSupported,
	"syz_proc_sys_generated_485":  alwaysSupported,
	"syz_proc_sys_generated_486":  alwaysSupported,
	"syz_proc_sys_generated_487":  alwaysSupported,
	"syz_proc_sys_generated_488":  alwaysSupported,
	"syz_proc_sys_generated_489":  alwaysSupported,
	"syz_proc_sys_generated_490":  alwaysSupported,
	"syz_proc_sys_generated_491":  alwaysSupported,
	"syz_proc_sys_generated_492":  alwaysSupported,
	"syz_proc_sys_generated_493":  alwaysSupported,
	"syz_proc_sys_generated_494":  alwaysSupported,
	"syz_proc_sys_generated_495":  alwaysSupported,
	"syz_proc_sys_generated_496":  alwaysSupported,
	"syz_proc_sys_generated_497":  alwaysSupported,
	"syz_proc_sys_generated_498":  alwaysSupported,
	"syz_proc_sys_generated_499":  alwaysSupported,
	"syz_proc_sys_generated_500":  alwaysSupported,
	"syz_proc_sys_generated_501":  alwaysSupported,
	"syz_proc_sys_generated_502":  alwaysSupported,
	"syz_proc_sys_generated_503":  alwaysSupported,
	"syz_proc_sys_generated_504":  alwaysSupported,
	"syz_proc_sys_generated_505":  alwaysSupported,
	"syz_proc_sys_generated_506":  alwaysSupported,
	"syz_proc_sys_generated_507":  alwaysSupported,
	"syz_proc_sys_generated_508":  alwaysSupported,
	"syz_proc_sys_generated_509":  alwaysSupported,
	"syz_proc_sys_generated_510":  alwaysSupported,
	"syz_proc_sys_generated_511":  alwaysSupported,
	"syz_proc_sys_generated_512":  alwaysSupported,
	"syz_proc_sys_generated_513":  alwaysSupported,
	"syz_proc_sys_generated_514":  alwaysSupported,
	"syz_proc_sys_generated_515":  alwaysSupported,
	"syz_proc_sys_generated_516":  alwaysSupported,
	"syz_proc_sys_generated_517":  alwaysSupported,
	"syz_proc_sys_generated_518":  alwaysSupported,
	"syz_proc_sys_generated_519":  alwaysSupported,
	"syz_proc_sys_generated_520":  alwaysSupported,
	"syz_proc_sys_generated_521":  alwaysSupported,
	"syz_proc_sys_generated_522":  alwaysSupported,
	"syz_proc_sys_generated_523":  alwaysSupported,
	"syz_proc_sys_generated_524":  alwaysSupported,
	"syz_proc_sys_generated_525":  alwaysSupported,
	"syz_proc_sys_generated_526":  alwaysSupported,
	"syz_proc_sys_generated_527":  alwaysSupported,
	"syz_proc_sys_generated_528":  alwaysSupported,
	"syz_proc_sys_generated_529":  alwaysSupported,
	"syz_proc_sys_generated_530":  alwaysSupported,
	"syz_proc_sys_generated_531":  alwaysSupported,
	"syz_proc_sys_generated_532":  alwaysSupported,
	"syz_proc_sys_generated_533":  alwaysSupported,
	"syz_proc_sys_generated_534":  alwaysSupported,
	"syz_proc_sys_generated_535":  alwaysSupported,
	"syz_proc_sys_generated_536":  alwaysSupported,
	"syz_proc_sys_generated_537":  alwaysSupported,
	"syz_proc_sys_generated_538":  alwaysSupported,
	"syz_proc_sys_generated_539":  alwaysSupported,
	"syz_proc_sys_generated_540":  alwaysSupported,
	"syz_proc_sys_generated_541":  alwaysSupported,
	"syz_proc_sys_generated_542":  alwaysSupported,
	"syz_proc_sys_generated_543":  alwaysSupported,
	"syz_proc_sys_generated_544":  alwaysSupported,
	"syz_proc_sys_generated_545":  alwaysSupported,
	"syz_proc_sys_generated_546":  alwaysSupported,
	"syz_proc_sys_generated_547":  alwaysSupported,
	"syz_proc_sys_generated_548":  alwaysSupported,
	"syz_proc_sys_generated_549":  alwaysSupported,
	"syz_proc_sys_generated_550":  alwaysSupported,
	"syz_proc_sys_generated_551":  alwaysSupported,
	"syz_proc_sys_generated_552":  alwaysSupported,
	"syz_proc_sys_generated_553":  alwaysSupported,
	"syz_proc_sys_generated_554":  alwaysSupported,
	"syz_proc_sys_generated_555":  alwaysSupported,
	"syz_proc_sys_generated_556":  alwaysSupported,
	"syz_proc_sys_generated_557":  alwaysSupported,
	"syz_proc_sys_generated_558":  alwaysSupported,
	"syz_proc_sys_generated_559":  alwaysSupported,
	"syz_proc_sys_generated_560":  alwaysSupported,
	"syz_proc_sys_generated_561":  alwaysSupported,
	"syz_proc_sys_generated_562":  alwaysSupported,
	"syz_proc_sys_generated_563":  alwaysSupported,
	"syz_proc_sys_generated_564":  alwaysSupported,
	"syz_proc_sys_generated_565":  alwaysSupported,
	"syz_proc_sys_generated_566":  alwaysSupported,
	"syz_proc_sys_generated_567":  alwaysSupported,
	"syz_proc_sys_generated_568":  alwaysSupported,
	"syz_proc_sys_generated_569":  alwaysSupported,
	"syz_proc_sys_generated_570":  alwaysSupported,
	"syz_proc_sys_generated_571":  alwaysSupported,
	"syz_proc_sys_generated_572":  alwaysSupported,
	"syz_proc_sys_generated_573":  alwaysSupported,
	"syz_proc_sys_generated_574":  alwaysSupported,
	"syz_proc_sys_generated_575":  alwaysSupported,
	"syz_proc_sys_generated_576":  alwaysSupported,
	"syz_proc_sys_generated_577":  alwaysSupported,
	"syz_proc_sys_generated_578":  alwaysSupported,
	"syz_proc_sys_generated_579":  alwaysSupported,
	"syz_proc_sys_generated_580":  alwaysSupported,
	"syz_proc_sys_generated_581":  alwaysSupported,
	"syz_proc_sys_generated_582":  alwaysSupported,
	"syz_proc_sys_generated_583":  alwaysSupported,
	"syz_proc_sys_generated_584":  alwaysSupported,
	"syz_proc_sys_generated_585":  alwaysSupported,
	"syz_proc_sys_generated_586":  alwaysSupported,
	"syz_proc_sys_generated_587":  alwaysSupported,
	"syz_proc_sys_generated_588":  alwaysSupported,
	"syz_proc_sys_generated_589":  alwaysSupported,
	"syz_proc_sys_generated_590":  alwaysSupported,
	"syz_proc_sys_generated_591":  alwaysSupported,
	"syz_proc_sys_generated_592":  alwaysSupported,
	"syz_proc_sys_generated_593":  alwaysSupported,
	"syz_proc_sys_generated_594":  alwaysSupported,
	"syz_proc_sys_generated_595":  alwaysSupported,
	"syz_proc_sys_generated_596":  alwaysSupported,
	"syz_proc_sys_generated_597":  alwaysSupported,
	"syz_proc_sys_generated_598":  alwaysSupported,
	"syz_proc_sys_generated_599":  alwaysSupported,
	"syz_proc_sys_generated_600":  alwaysSupported,
	"syz_proc_sys_generated_601":  alwaysSupported,
	"syz_proc_sys_generated_602":  alwaysSupported,
	"syz_proc_sys_generated_603":  alwaysSupported,
	"syz_proc_sys_generated_604":  alwaysSupported,
	"syz_proc_sys_generated_605":  alwaysSupported,
	"syz_proc_sys_generated_606":  alwaysSupported,
	"syz_proc_sys_generated_607":  alwaysSupported,
	"syz_proc_sys_generated_608":  alwaysSupported,
	"syz_proc_sys_generated_609":  alwaysSupported,
	"syz_proc_sys_generated_610":  alwaysSupported,
	"syz_proc_sys_generated_611":  alwaysSupported,
	"syz_proc_sys_generated_612":  alwaysSupported,
	"syz_proc_sys_generated_613":  alwaysSupported,
	"syz_proc_sys_generated_614":  alwaysSupported,
	"syz_proc_sys_generated_615":  alwaysSupported,
	"syz_proc_sys_generated_616":  alwaysSupported,
	"syz_proc_sys_generated_617":  alwaysSupported,
	"syz_proc_sys_generated_618":  alwaysSupported,
	"syz_proc_sys_generated_619":  alwaysSupported,
	"syz_proc_sys_generated_620":  alwaysSupported,
	"syz_proc_sys_generated_621":  alwaysSupported,
	"syz_proc_sys_generated_622":  alwaysSupported,
	"syz_proc_sys_generated_623":  alwaysSupported,
	"syz_proc_sys_generated_624":  alwaysSupported,
	"syz_proc_sys_generated_625":  alwaysSupported,
	"syz_proc_sys_generated_626":  alwaysSupported,
	"syz_proc_sys_generated_627":  alwaysSupported,
	"syz_proc_sys_generated_628":  alwaysSupported,
	"syz_proc_sys_generated_629":  alwaysSupported,
	"syz_proc_sys_generated_630":  alwaysSupported,
	"syz_proc_sys_generated_631":  alwaysSupported,
	"syz_proc_sys_generated_632":  alwaysSupported,
	"syz_proc_sys_generated_633":  alwaysSupported,
	"syz_proc_sys_generated_634":  alwaysSupported,
	"syz_proc_sys_generated_635":  alwaysSupported,
	"syz_proc_sys_generated_636":  alwaysSupported,
	"syz_proc_sys_generated_637":  alwaysSupported,
	"syz_proc_sys_generated_638":  alwaysSupported,
	"syz_proc_sys_generated_639":  alwaysSupported,
	"syz_proc_sys_generated_640":  alwaysSupported,
	"syz_proc_sys_generated_641":  alwaysSupported,
	"syz_proc_sys_generated_642":  alwaysSupported,
	"syz_proc_sys_generated_643":  alwaysSupported,
	"syz_proc_sys_generated_644":  alwaysSupported,
	"syz_proc_sys_generated_645":  alwaysSupported,
	"syz_proc_sys_generated_646":  alwaysSupported,
	"syz_proc_sys_generated_647":  alwaysSupported,
	"syz_proc_sys_generated_648":  alwaysSupported,
	"syz_proc_sys_generated_649":  alwaysSupported,
	"syz_proc_sys_generated_650":  alwaysSupported,
	"syz_proc_sys_generated_651":  alwaysSupported,
	"syz_proc_sys_generated_652":  alwaysSupported,
	"syz_proc_sys_generated_653":  alwaysSupported,
	"syz_proc_sys_generated_654":  alwaysSupported,
	"syz_proc_sys_generated_655":  alwaysSupported,
	"syz_proc_sys_generated_656":  alwaysSupported,
	"syz_proc_sys_generated_657":  alwaysSupported,
	"syz_proc_sys_generated_658":  alwaysSupported,
	"syz_proc_sys_generated_659":  alwaysSupported,
	"syz_proc_sys_generated_660":  alwaysSupported,
	"syz_proc_sys_generated_661":  alwaysSupported,
	"syz_proc_sys_generated_662":  alwaysSupported,
	"syz_proc_sys_generated_663":  alwaysSupported,
	"syz_proc_sys_generated_664":  alwaysSupported,
	"syz_proc_sys_generated_665":  alwaysSupported,
	"syz_proc_sys_generated_666":  alwaysSupported,
	"syz_proc_sys_generated_667":  alwaysSupported,
	"syz_proc_sys_generated_668":  alwaysSupported,
	"syz_proc_sys_generated_669":  alwaysSupported,
	"syz_proc_sys_generated_670":  alwaysSupported,
	"syz_proc_sys_generated_671":  alwaysSupported,
	"syz_proc_sys_generated_672":  alwaysSupported,
	"syz_proc_sys_generated_673":  alwaysSupported,
	"syz_proc_sys_generated_674":  alwaysSupported,
	"syz_proc_sys_generated_675":  alwaysSupported,
	"syz_proc_sys_generated_676":  alwaysSupported,
	"syz_proc_sys_generated_677":  alwaysSupported,
	"syz_proc_sys_generated_678":  alwaysSupported,
	"syz_proc_sys_generated_679":  alwaysSupported,
	"syz_proc_sys_generated_680":  alwaysSupported,
	"syz_proc_sys_generated_681":  alwaysSupported,
	"syz_proc_sys_generated_682":  alwaysSupported,
	"syz_proc_sys_generated_683":  alwaysSupported,
	"syz_proc_sys_generated_684":  alwaysSupported,
	"syz_proc_sys_generated_685":  alwaysSupported,
	"syz_proc_sys_generated_686":  alwaysSupported,
	"syz_proc_sys_generated_687":  alwaysSupported,
	"syz_proc_sys_generated_688":  alwaysSupported,
	"syz_proc_sys_generated_689":  alwaysSupported,
	"syz_proc_sys_generated_690":  alwaysSupported,
	"syz_proc_sys_generated_691":  alwaysSupported,
	"syz_proc_sys_generated_692":  alwaysSupported,
	"syz_proc_sys_generated_693":  alwaysSupported,
	"syz_proc_sys_generated_694":  alwaysSupported,
	"syz_proc_sys_generated_695":  alwaysSupported,
	"syz_proc_sys_generated_696":  alwaysSupported,
	"syz_proc_sys_generated_697":  alwaysSupported,
	"syz_proc_sys_generated_698":  alwaysSupported,
	"syz_proc_sys_generated_699":  alwaysSupported,
	"syz_proc_sys_generated_700":  alwaysSupported,
	"syz_proc_sys_generated_701":  alwaysSupported,
	"syz_proc_sys_generated_702":  alwaysSupported,
	"syz_proc_sys_generated_703":  alwaysSupported,
	"syz_proc_sys_generated_704":  alwaysSupported,
	"syz_proc_sys_generated_705":  alwaysSupported,
	"syz_proc_sys_generated_706":  alwaysSupported,
	"syz_proc_sys_generated_707":  alwaysSupported,
	"syz_proc_sys_generated_708":  alwaysSupported,
	"syz_proc_sys_generated_709":  alwaysSupported,
	"syz_proc_sys_generated_710":  alwaysSupported,
	"syz_proc_sys_generated_711":  alwaysSupported,
	"syz_proc_sys_generated_712":  alwaysSupported,
	"syz_proc_sys_generated_713":  alwaysSupported,
	"syz_proc_sys_generated_714":  alwaysSupported,
	"syz_proc_sys_generated_715":  alwaysSupported,
	"syz_proc_sys_generated_716":  alwaysSupported,
	"syz_proc_sys_generated_717":  alwaysSupported,
	"syz_proc_sys_generated_718":  alwaysSupported,
	"syz_proc_sys_generated_719":  alwaysSupported,
	"syz_proc_sys_generated_720":  alwaysSupported,
	"syz_proc_sys_generated_721":  alwaysSupported,
	"syz_proc_sys_generated_722":  alwaysSupported,
	"syz_proc_sys_generated_723":  alwaysSupported,
	"syz_proc_sys_generated_724":  alwaysSupported,
	"syz_proc_sys_generated_725":  alwaysSupported,
	"syz_proc_sys_generated_726":  alwaysSupported,
	"syz_proc_sys_generated_727":  alwaysSupported,
	"syz_proc_sys_generated_728":  alwaysSupported,
	"syz_proc_sys_generated_729":  alwaysSupported,
	"syz_proc_sys_generated_730":  alwaysSupported,
	"syz_proc_sys_generated_731":  alwaysSupported,
	"syz_proc_sys_generated_732":  alwaysSupported,
	"syz_proc_sys_generated_733":  alwaysSupported,
	"syz_proc_sys_generated_734":  alwaysSupported,
	"syz_proc_sys_generated_735":  alwaysSupported,
	"syz_proc_sys_generated_736":  alwaysSupported,
	"syz_proc_sys_generated_737":  alwaysSupported,
	"syz_proc_sys_generated_738":  alwaysSupported,
	"syz_proc_sys_generated_739":  alwaysSupported,
	"syz_proc_sys_generated_740":  alwaysSupported,
	"syz_proc_sys_generated_741":  alwaysSupported,
	"syz_proc_sys_generated_742":  alwaysSupported,
	"syz_proc_sys_generated_743":  alwaysSupported,
	"syz_proc_sys_generated_744":  alwaysSupported,
	"syz_proc_sys_generated_745":  alwaysSupported,
	"syz_proc_sys_generated_746":  alwaysSupported,
	"syz_proc_sys_generated_747":  alwaysSupported,
	"syz_proc_sys_generated_748":  alwaysSupported,
	"syz_proc_sys_generated_749":  alwaysSupported,
	"syz_proc_sys_generated_750":  alwaysSupported,
	"syz_proc_sys_generated_751":  alwaysSupported,
	"syz_proc_sys_generated_752":  alwaysSupported,
	"syz_proc_sys_generated_753":  alwaysSupported,
	"syz_proc_sys_generated_754":  alwaysSupported,
	"syz_proc_sys_generated_755":  alwaysSupported,
	"syz_proc_sys_generated_756":  alwaysSupported,
	"syz_proc_sys_generated_757":  alwaysSupported,
	"syz_proc_sys_generated_758":  alwaysSupported,
	"syz_proc_sys_generated_759":  alwaysSupported,
	"syz_proc_sys_generated_760":  alwaysSupported,
	"syz_proc_sys_generated_761":  alwaysSupported,
	"syz_proc_sys_generated_762":  alwaysSupported,
	"syz_proc_sys_generated_763":  alwaysSupported,
	"syz_proc_sys_generated_764":  alwaysSupported,
	"syz_proc_sys_generated_765":  alwaysSupported,
	"syz_proc_sys_generated_766":  alwaysSupported,
	"syz_proc_sys_generated_767":  alwaysSupported,
	"syz_proc_sys_generated_768":  alwaysSupported,
	"syz_proc_sys_generated_769":  alwaysSupported,
	"syz_proc_sys_generated_770":  alwaysSupported,
	"syz_proc_sys_generated_771":  alwaysSupported,
	"syz_proc_sys_generated_772":  alwaysSupported,
	"syz_proc_sys_generated_773":  alwaysSupported,
	"syz_proc_sys_generated_774":  alwaysSupported,
	"syz_proc_sys_generated_775":  alwaysSupported,
	"syz_proc_sys_generated_776":  alwaysSupported,
	"syz_proc_sys_generated_777":  alwaysSupported,
	"syz_proc_sys_generated_778":  alwaysSupported,
	"syz_proc_sys_generated_779":  alwaysSupported,
	"syz_proc_sys_generated_780":  alwaysSupported,
	"syz_proc_sys_generated_781":  alwaysSupported,
	"syz_proc_sys_generated_782":  alwaysSupported,
	"syz_proc_sys_generated_783":  alwaysSupported,
	"syz_proc_sys_generated_784":  alwaysSupported,
	"syz_proc_sys_generated_785":  alwaysSupported,
	"syz_proc_sys_generated_786":  alwaysSupported,
	"syz_proc_sys_generated_787":  alwaysSupported,
	"syz_proc_sys_generated_788":  alwaysSupported,
	"syz_proc_sys_generated_789":  alwaysSupported,
	"syz_proc_sys_generated_790":  alwaysSupported,
	"syz_proc_sys_generated_791":  alwaysSupported,
	"syz_proc_sys_generated_792":  alwaysSupported,
	"syz_proc_sys_generated_793":  alwaysSupported,
	"syz_proc_sys_generated_794":  alwaysSupported,
	"syz_proc_sys_generated_795":  alwaysSupported,
	"syz_proc_sys_generated_796":  alwaysSupported,
	"syz_proc_sys_generated_797":  alwaysSupported,
	"syz_proc_sys_generated_798":  alwaysSupported,
	"syz_proc_sys_generated_799":  alwaysSupported,
	"syz_proc_sys_generated_800":  alwaysSupported,
	"syz_proc_sys_generated_801":  alwaysSupported,
	"syz_proc_sys_generated_802":  alwaysSupported,
	"syz_proc_sys_generated_803":  alwaysSupported,
	"syz_proc_sys_generated_804":  alwaysSupported,
	"syz_proc_sys_generated_805":  alwaysSupported,
	"syz_proc_sys_generated_806":  alwaysSupported,
	"syz_proc_sys_generated_807":  alwaysSupported,
	"syz_proc_sys_generated_808":  alwaysSupported,
	"syz_proc_sys_generated_809":  alwaysSupported,
	"syz_proc_sys_generated_810":  alwaysSupported,
	"syz_proc_sys_generated_811":  alwaysSupported,
	"syz_proc_sys_generated_812":  alwaysSupported,
	"syz_proc_sys_generated_813":  alwaysSupported,
	"syz_proc_sys_generated_814":  alwaysSupported,
	"syz_proc_sys_generated_815":  alwaysSupported,
	"syz_proc_sys_generated_816":  alwaysSupported,
	"syz_proc_sys_generated_817":  alwaysSupported,
	"syz_proc_sys_generated_818":  alwaysSupported,
	"syz_proc_sys_generated_819":  alwaysSupported,
	"syz_proc_sys_generated_820":  alwaysSupported,
	"syz_proc_sys_generated_821":  alwaysSupported,
	"syz_proc_sys_generated_822":  alwaysSupported,
	"syz_proc_sys_generated_823":  alwaysSupported,
	"syz_proc_sys_generated_824":  alwaysSupported,
	"syz_proc_sys_generated_825":  alwaysSupported,
	"syz_proc_sys_generated_826":  alwaysSupported,
	"syz_proc_sys_generated_827":  alwaysSupported,
	"syz_proc_sys_generated_828":  alwaysSupported,
	"syz_proc_sys_generated_829":  alwaysSupported,
	"syz_proc_sys_generated_830":  alwaysSupported,
	"syz_proc_sys_generated_831":  alwaysSupported,
	"syz_proc_sys_generated_832":  alwaysSupported,
	"syz_proc_sys_generated_833":  alwaysSupported,
	"syz_proc_sys_generated_834":  alwaysSupported,
	"syz_proc_sys_generated_835":  alwaysSupported,
	"syz_proc_sys_generated_836":  alwaysSupported,
	"syz_proc_sys_generated_837":  alwaysSupported,
	"syz_proc_sys_generated_838":  alwaysSupported,
	"syz_proc_sys_generated_839":  alwaysSupported,
	"syz_proc_sys_generated_840":  alwaysSupported,
	"syz_proc_sys_generated_841":  alwaysSupported,
	"syz_proc_sys_generated_842":  alwaysSupported,
	"syz_proc_sys_generated_843":  alwaysSupported,
	"syz_proc_sys_generated_844":  alwaysSupported,
	"syz_proc_sys_generated_845":  alwaysSupported,
	"syz_proc_sys_generated_846":  alwaysSupported,
	"syz_proc_sys_generated_847":  alwaysSupported,
	"syz_proc_sys_generated_848":  alwaysSupported,
	"syz_proc_sys_generated_849":  alwaysSupported,
	"syz_proc_sys_generated_850":  alwaysSupported,
	"syz_proc_sys_generated_851":  alwaysSupported,
	"syz_proc_sys_generated_852":  alwaysSupported,
	"syz_proc_sys_generated_853":  alwaysSupported,
	"syz_proc_sys_generated_854":  alwaysSupported,
	"syz_proc_sys_generated_855":  alwaysSupported,
	"syz_proc_sys_generated_856":  alwaysSupported,
	"syz_proc_sys_generated_857":  alwaysSupported,
	"syz_proc_sys_generated_858":  alwaysSupported,
	"syz_proc_sys_generated_859":  alwaysSupported,
	"syz_proc_sys_generated_860":  alwaysSupported,
	"syz_proc_sys_generated_861":  alwaysSupported,
	"syz_proc_sys_generated_862":  alwaysSupported,
	"syz_proc_sys_generated_863":  alwaysSupported,
	"syz_proc_sys_generated_864":  alwaysSupported,
	"syz_proc_sys_generated_865":  alwaysSupported,
	"syz_proc_sys_generated_866":  alwaysSupported,
	"syz_proc_sys_generated_867":  alwaysSupported,
	"syz_proc_sys_generated_868":  alwaysSupported,
	"syz_proc_sys_generated_869":  alwaysSupported,
	"syz_proc_sys_generated_870":  alwaysSupported,
	"syz_proc_sys_generated_871":  alwaysSupported,
	"syz_proc_sys_generated_872":  alwaysSupported,
	"syz_proc_sys_generated_873":  alwaysSupported,
	"syz_proc_sys_generated_874":  alwaysSupported,
	"syz_proc_sys_generated_875":  alwaysSupported,
	"syz_proc_sys_generated_876":  alwaysSupported,
	"syz_proc_sys_generated_877":  alwaysSupported,
	"syz_proc_sys_generated_878":  alwaysSupported,
	"syz_proc_sys_generated_879":  alwaysSupported,
	"syz_proc_sys_generated_880":  alwaysSupported,
	"syz_proc_sys_generated_881":  alwaysSupported,
	"syz_proc_sys_generated_882":  alwaysSupported,
	"syz_proc_sys_generated_883":  alwaysSupported,
	"syz_proc_sys_generated_884":  alwaysSupported,
	"syz_proc_sys_generated_885":  alwaysSupported,
	"syz_proc_sys_generated_886":  alwaysSupported,
	"syz_proc_sys_generated_887":  alwaysSupported,
	"syz_proc_sys_generated_888":  alwaysSupported,
	"syz_proc_sys_generated_889":  alwaysSupported,
	"syz_proc_sys_generated_890":  alwaysSupported,
	"syz_proc_sys_generated_891":  alwaysSupported,
	"syz_proc_sys_generated_892":  alwaysSupported,
	"syz_proc_sys_generated_893":  alwaysSupported,
	"syz_proc_sys_generated_894":  alwaysSupported,
	"syz_proc_sys_generated_895":  alwaysSupported,
	"syz_proc_sys_generated_896":  alwaysSupported,
	"syz_proc_sys_generated_897":  alwaysSupported,
	"syz_proc_sys_generated_898":  alwaysSupported,
	"syz_proc_sys_generated_899":  alwaysSupported,
	"syz_proc_sys_generated_900":  alwaysSupported,
	"syz_proc_sys_generated_901":  alwaysSupported,
	"syz_proc_sys_generated_902":  alwaysSupported,
	"syz_proc_sys_generated_903":  alwaysSupported,
	"syz_proc_sys_generated_904":  alwaysSupported,
	"syz_proc_sys_generated_905":  alwaysSupported,
	"syz_proc_sys_generated_906":  alwaysSupported,
	"syz_proc_sys_generated_907":  alwaysSupported,
	"syz_proc_sys_generated_908":  alwaysSupported,
	"syz_proc_sys_generated_909":  alwaysSupported,
	"syz_proc_sys_generated_910":  alwaysSupported,
	"syz_proc_sys_generated_911":  alwaysSupported,
	"syz_proc_sys_generated_912":  alwaysSupported,
	"syz_proc_sys_generated_913":  alwaysSupported,
	"syz_proc_sys_generated_914":  alwaysSupported,
	"syz_proc_sys_generated_915":  alwaysSupported,
	"syz_proc_sys_generated_916":  alwaysSupported,
	"syz_proc_sys_generated_917":  alwaysSupported,
	"syz_proc_sys_generated_918":  alwaysSupported,
	"syz_proc_sys_generated_919":  alwaysSupported,
	"syz_proc_sys_generated_920":  alwaysSupported,
	"syz_proc_sys_generated_921":  alwaysSupported,
	"syz_proc_sys_generated_922":  alwaysSupported,
	"syz_proc_sys_generated_923":  alwaysSupported,
	"syz_proc_sys_generated_924":  alwaysSupported,
	"syz_proc_sys_generated_925":  alwaysSupported,
	"syz_proc_sys_generated_926":  alwaysSupported,
	"syz_proc_sys_generated_927":  alwaysSupported,
	"syz_proc_sys_generated_928":  alwaysSupported,
	"syz_proc_sys_generated_929":  alwaysSupported,
	"syz_proc_sys_generated_930":  alwaysSupported,
	"syz_proc_sys_generated_931":  alwaysSupported,
	"syz_proc_sys_generated_932":  alwaysSupported,
	"syz_proc_sys_generated_933":  alwaysSupported,
	"syz_proc_sys_generated_934":  alwaysSupported,
	"syz_proc_sys_generated_935":  alwaysSupported,
	"syz_proc_sys_generated_936":  alwaysSupported,
	"syz_proc_sys_generated_937":  alwaysSupported,
	"syz_proc_sys_generated_938":  alwaysSupported,
	"syz_proc_sys_generated_939":  alwaysSupported,
	"syz_proc_sys_generated_940":  alwaysSupported,
	"syz_proc_sys_generated_941":  alwaysSupported,
	"syz_proc_sys_generated_942":  alwaysSupported,
	"syz_proc_sys_generated_943":  alwaysSupported,
	"syz_proc_sys_generated_944":  alwaysSupported,
	"syz_proc_sys_generated_945":  alwaysSupported,
	"syz_proc_sys_generated_946":  alwaysSupported,
	"syz_proc_sys_generated_947":  alwaysSupported,
	"syz_proc_sys_generated_948":  alwaysSupported,
	"syz_proc_sys_generated_949":  alwaysSupported,
	"syz_proc_sys_generated_950":  alwaysSupported,
	"syz_proc_sys_generated_951":  alwaysSupported,
	"syz_proc_sys_generated_952":  alwaysSupported,
	"syz_proc_sys_generated_953":  alwaysSupported,
	"syz_proc_sys_generated_954":  alwaysSupported,
	"syz_proc_sys_generated_955":  alwaysSupported,
	"syz_proc_sys_generated_956":  alwaysSupported,
	"syz_proc_sys_generated_957":  alwaysSupported,
	"syz_proc_sys_generated_958":  alwaysSupported,
	"syz_proc_sys_generated_959":  alwaysSupported,
	"syz_proc_sys_generated_960":  alwaysSupported,
	"syz_proc_sys_generated_961":  alwaysSupported,
	"syz_proc_sys_generated_962":  alwaysSupported,
	"syz_proc_sys_generated_963":  alwaysSupported,
	"syz_proc_sys_generated_964":  alwaysSupported,
	"syz_proc_sys_generated_965":  alwaysSupported,
	"syz_proc_sys_generated_966":  alwaysSupported,
	"syz_proc_sys_generated_967":  alwaysSupported,
	"syz_proc_sys_generated_968":  alwaysSupported,
	"syz_proc_sys_generated_969":  alwaysSupported,
	"syz_proc_sys_generated_970":  alwaysSupported,
	"syz_proc_sys_generated_971":  alwaysSupported,
	"syz_proc_sys_generated_972":  alwaysSupported,
	"syz_proc_sys_generated_973":  alwaysSupported,
	"syz_proc_sys_generated_974":  alwaysSupported,
	"syz_proc_sys_generated_975":  alwaysSupported,
	"syz_proc_sys_generated_976":  alwaysSupported,
	"syz_proc_sys_generated_977":  alwaysSupported,
	"syz_proc_sys_generated_978":  alwaysSupported,
	"syz_proc_sys_generated_979":  alwaysSupported,
	"syz_proc_sys_generated_980":  alwaysSupported,
	"syz_proc_sys_generated_981":  alwaysSupported,
	"syz_proc_sys_generated_982":  alwaysSupported,
	"syz_proc_sys_generated_983":  alwaysSupported,
	"syz_proc_sys_generated_984":  alwaysSupported,
	"syz_proc_sys_generated_985":  alwaysSupported,
	"syz_proc_sys_generated_986":  alwaysSupported,
	"syz_proc_sys_generated_987":  alwaysSupported,
	"syz_proc_sys_generated_988":  alwaysSupported,
	"syz_proc_sys_generated_989":  alwaysSupported,
	"syz_proc_sys_generated_990":  alwaysSupported,
	"syz_proc_sys_generated_991":  alwaysSupported,
	"syz_proc_sys_generated_992":  alwaysSupported,
	"syz_proc_sys_generated_993":  alwaysSupported,
	"syz_proc_sys_generated_994":  alwaysSupported,
	"syz_proc_sys_generated_995":  alwaysSupported,
	"syz_proc_sys_generated_996":  alwaysSupported,
	"syz_proc_sys_generated_997":  alwaysSupported,
	"syz_proc_sys_generated_998":  alwaysSupported,
	"syz_proc_sys_generated_999":  alwaysSupported,
	"syz_proc_sys_generated_1000": alwaysSupported,
	"syz_proc_sys_generated_1001": alwaysSupported,
	"syz_proc_sys_generated_1002": alwaysSupported,
	"syz_proc_sys_generated_1003": alwaysSupported,
	"syz_proc_sys_generated_1004": alwaysSupported,
	"syz_proc_sys_generated_1005": alwaysSupported,
	"syz_proc_sys_generated_1006": alwaysSupported,
	"syz_proc_sys_generated_1007": alwaysSupported,
	"syz_proc_sys_generated_1008": alwaysSupported,
	"syz_proc_sys_generated_1009": alwaysSupported,
	"syz_proc_sys_generated_1010": alwaysSupported,
	"syz_proc_sys_generated_1011": alwaysSupported,
	"syz_proc_sys_generated_1012": alwaysSupported,
	"syz_proc_sys_generated_1013": alwaysSupported,
	"syz_proc_sys_generated_1014": alwaysSupported,
	"syz_proc_sys_generated_1015": alwaysSupported,
	"syz_proc_sys_generated_1016": alwaysSupported,
	"syz_proc_sys_generated_1017": alwaysSupported,
	"syz_proc_sys_generated_1018": alwaysSupported,
	"syz_proc_sys_generated_1019": alwaysSupported,
	"syz_proc_sys_generated_1020": alwaysSupported,
	"syz_proc_sys_generated_1021": alwaysSupported,
	"syz_proc_sys_generated_1022": alwaysSupported,
	"syz_proc_sys_generated_1023": alwaysSupported,
	"syz_proc_sys_generated_1024": alwaysSupported,
	"syz_proc_sys_generated_1025": alwaysSupported,
	"syz_proc_sys_generated_1026": alwaysSupported,
	"syz_proc_sys_generated_1027": alwaysSupported,
	"syz_proc_sys_generated_1028": alwaysSupported,
	"syz_proc_sys_generated_1029": alwaysSupported,
	"syz_proc_sys_generated_1030": alwaysSupported,
	"syz_proc_sys_generated_1031": alwaysSupported,
	"syz_proc_sys_generated_1032": alwaysSupported,
	"syz_proc_sys_generated_1033": alwaysSupported,
	"syz_proc_sys_generated_1034": alwaysSupported,
	"syz_proc_sys_generated_1035": alwaysSupported,
	"syz_proc_sys_generated_1036": alwaysSupported,
	"syz_proc_sys_generated_1037": alwaysSupported,
	"syz_proc_sys_generated_1038": alwaysSupported,
	"syz_proc_sys_generated_1039": alwaysSupported,
	"syz_proc_sys_generated_1040": alwaysSupported,
	"syz_proc_sys_generated_1041": alwaysSupported,
	"syz_proc_sys_generated_1042": alwaysSupported,
	"syz_proc_sys_generated_1043": alwaysSupported,
	"syz_proc_sys_generated_1044": alwaysSupported,
	"syz_proc_sys_generated_1045": alwaysSupported,
	"syz_proc_sys_generated_1046": alwaysSupported,
	"syz_proc_sys_generated_1047": alwaysSupported,
	"syz_proc_sys_generated_1048": alwaysSupported,
	"syz_proc_sys_generated_1049": alwaysSupported,
	"syz_proc_sys_generated_1050": alwaysSupported,
	"syz_proc_sys_generated_1051": alwaysSupported,
	"syz_proc_sys_generated_1052": alwaysSupported,
	"syz_proc_sys_generated_1053": alwaysSupported,
	"syz_proc_sys_generated_1054": alwaysSupported,
	"syz_proc_sys_generated_1055": alwaysSupported,
	"syz_proc_sys_generated_1056": alwaysSupported,
	"syz_proc_sys_generated_1057": alwaysSupported,
	"syz_proc_sys_generated_1058": alwaysSupported,
	"syz_proc_sys_generated_1059": alwaysSupported,
	"syz_proc_sys_generated_1060": alwaysSupported,
	"syz_proc_sys_generated_1061": alwaysSupported,
	"syz_proc_sys_generated_1062": alwaysSupported,
	"syz_proc_sys_generated_1063": alwaysSupported,
	"syz_proc_sys_generated_1064": alwaysSupported,
	"syz_proc_sys_generated_1065": alwaysSupported,
	"syz_proc_sys_generated_1066": alwaysSupported,
	"syz_proc_sys_generated_1067": alwaysSupported,
	"syz_proc_sys_generated_1068": alwaysSupported,
	"syz_proc_sys_generated_1069": alwaysSupported,
	"syz_proc_sys_generated_1070": alwaysSupported,
	"syz_proc_sys_generated_1071": alwaysSupported,
	"syz_proc_sys_generated_1072": alwaysSupported,
	"syz_proc_sys_generated_1073": alwaysSupported,
	"syz_proc_sys_generated_1074": alwaysSupported,
	"syz_proc_sys_generated_1075": alwaysSupported,
	"syz_proc_sys_generated_1076": alwaysSupported,
	"syz_proc_sys_generated_1077": alwaysSupported,
	"syz_proc_sys_generated_1078": alwaysSupported,
	"syz_proc_sys_generated_1079": alwaysSupported,
	"syz_proc_sys_generated_1080": alwaysSupported,
	"syz_proc_sys_generated_1081": alwaysSupported,
	"syz_proc_sys_generated_1082": alwaysSupported,
	"syz_proc_sys_generated_1083": alwaysSupported,
	"syz_proc_sys_generated_1084": alwaysSupported,
	"syz_proc_sys_generated_1085": alwaysSupported,
	"syz_proc_sys_generated_1086": alwaysSupported,
	"syz_proc_sys_generated_1087": alwaysSupported,
	"syz_proc_sys_generated_1088": alwaysSupported,
	"syz_proc_sys_generated_1089": alwaysSupported,
	"syz_proc_sys_generated_1090": alwaysSupported,
	"syz_proc_sys_generated_1091": alwaysSupported,
	"syz_proc_sys_generated_1092": alwaysSupported,
	"syz_proc_sys_generated_1093": alwaysSupported,
	"syz_proc_sys_generated_1094": alwaysSupported,
	"syz_proc_sys_generated_1095": alwaysSupported,
	"syz_proc_sys_generated_1096": alwaysSupported,
	"syz_proc_sys_generated_1097": alwaysSupported,
	"syz_proc_sys_generated_1098": alwaysSupported,
	"syz_proc_sys_generated_1099": alwaysSupported,
	"syz_proc_sys_generated_1100": alwaysSupported,
	"syz_proc_sys_generated_1101": alwaysSupported,
	"syz_proc_sys_generated_1102": alwaysSupported,
	"syz_proc_sys_generated_1103": alwaysSupported,
	"syz_proc_sys_generated_1104": alwaysSupported,
	"syz_proc_sys_generated_1105": alwaysSupported,
	"syz_proc_sys_generated_1106": alwaysSupported,
	"syz_proc_sys_generated_1107": alwaysSupported,
	"syz_proc_sys_generated_1108": alwaysSupported,
	"syz_proc_sys_generated_1109": alwaysSupported,
	"syz_proc_sys_generated_1110": alwaysSupported,
	"syz_proc_sys_generated_1111": alwaysSupported,
	"syz_proc_sys_generated_1112": alwaysSupported,
	"syz_proc_sys_generated_1113": alwaysSupported,
	"syz_proc_sys_generated_1114": alwaysSupported,
	"syz_proc_sys_generated_1115": alwaysSupported,
	"syz_proc_sys_generated_1116": alwaysSupported,
	"syz_proc_sys_generated_1117": alwaysSupported,
	"syz_proc_sys_generated_1118": alwaysSupported,
	"syz_proc_sys_generated_1119": alwaysSupported,
	"syz_proc_sys_generated_1120": alwaysSupported,
	"syz_proc_sys_generated_1121": alwaysSupported,
	"syz_proc_sys_generated_1122": alwaysSupported,
	"syz_proc_sys_generated_1123": alwaysSupported,
	"syz_proc_sys_generated_1124": alwaysSupported,
	"syz_proc_sys_generated_1125": alwaysSupported,
	"syz_proc_sys_generated_1126": alwaysSupported,
	"syz_proc_sys_generated_1127": alwaysSupported,
	"syz_proc_sys_generated_1128": alwaysSupported,
	"syz_proc_sys_generated_1129": alwaysSupported,
	"syz_proc_sys_generated_1130": alwaysSupported,
	"syz_proc_sys_generated_1131": alwaysSupported,
	"syz_proc_sys_generated_1132": alwaysSupported,
	"syz_proc_sys_generated_1133": alwaysSupported,
	"syz_proc_sys_generated_1134": alwaysSupported,
	"syz_proc_sys_generated_1135": alwaysSupported,
	"syz_proc_sys_generated_1136": alwaysSupported,
	"syz_proc_sys_generated_1137": alwaysSupported,
	"syz_proc_sys_generated_1138": alwaysSupported,
	"syz_proc_sys_generated_1139": alwaysSupported,
	"syz_proc_sys_generated_1140": alwaysSupported,
	"syz_proc_sys_generated_1141": alwaysSupported,
	"syz_proc_sys_generated_1142": alwaysSupported,
	"syz_proc_sys_generated_1143": alwaysSupported,
	"syz_proc_sys_generated_1144": alwaysSupported,
	"syz_proc_sys_generated_1145": alwaysSupported,
	"syz_proc_sys_generated_1146": alwaysSupported,
	"syz_proc_sys_generated_1147": alwaysSupported,
	"syz_proc_sys_generated_1148": alwaysSupported,
	"syz_proc_sys_generated_1149": alwaysSupported,
	"syz_proc_sys_generated_1150": alwaysSupported,
	"syz_proc_sys_generated_1151": alwaysSupported,
	"syz_proc_sys_generated_1152": alwaysSupported,
	"syz_proc_sys_generated_1153": alwaysSupported,
	"syz_proc_sys_generated_1154": alwaysSupported,
	"syz_proc_sys_generated_1155": alwaysSupported,
	"syz_proc_sys_generated_1156": alwaysSupported,
	"syz_proc_sys_generated_1157": alwaysSupported,
	"syz_proc_sys_generated_1158": alwaysSupported,
	"syz_proc_sys_generated_1159": alwaysSupported,
	"syz_proc_sys_generated_1160": alwaysSupported,
	"syz_proc_sys_generated_1161": alwaysSupported,
	"syz_proc_sys_generated_1162": alwaysSupported,
	"syz_proc_sys_generated_1163": alwaysSupported,
	"syz_proc_sys_generated_1164": alwaysSupported,
	"syz_proc_sys_generated_1165": alwaysSupported,
	"syz_proc_sys_generated_1166": alwaysSupported,
	"syz_proc_sys_generated_1167": alwaysSupported,
	"syz_proc_sys_generated_1168": alwaysSupported,
	"syz_proc_sys_generated_1169": alwaysSupported,
	"syz_proc_sys_generated_1170": alwaysSupported,
	"syz_proc_sys_generated_1171": alwaysSupported,
	"syz_proc_sys_generated_1172": alwaysSupported,
	"syz_proc_sys_generated_1173": alwaysSupported,
	"syz_proc_sys_generated_1174": alwaysSupported,
	"syz_proc_sys_generated_1175": alwaysSupported,
	"syz_proc_sys_generated_1176": alwaysSupported,
	"syz_proc_sys_generated_1177": alwaysSupported,
	"syz_proc_sys_generated_1178": alwaysSupported,
	"syz_proc_sys_generated_1179": alwaysSupported,
	"syz_proc_sys_generated_1180": alwaysSupported,
	"syz_proc_sys_generated_1181": alwaysSupported,
	"syz_proc_sys_generated_1182": alwaysSupported,
	"syz_proc_sys_generated_1183": alwaysSupported,
	"syz_proc_sys_generated_1184": alwaysSupported,
	"syz_proc_sys_generated_1185": alwaysSupported,
	"syz_proc_sys_generated_1186": alwaysSupported,
	"syz_proc_sys_generated_1187": alwaysSupported,
	"syz_proc_sys_generated_1188": alwaysSupported,
	"syz_proc_sys_generated_1189": alwaysSupported,
	"syz_proc_sys_generated_1190": alwaysSupported,
	"syz_proc_sys_generated_1191": alwaysSupported,
	"syz_proc_sys_generated_1192": alwaysSupported,
	"syz_proc_sys_generated_1193": alwaysSupported,
	"syz_proc_sys_generated_1194": alwaysSupported,
	"syz_proc_sys_generated_1195": alwaysSupported,
	"syz_proc_sys_generated_1196": alwaysSupported,
	"syz_proc_sys_generated_1197": alwaysSupported,
	"syz_proc_sys_generated_1198": alwaysSupported,
	"syz_proc_sys_generated_1199": alwaysSupported,
	"syz_proc_sys_generated_1200": alwaysSupported,
	"syz_proc_sys_generated_1201": alwaysSupported,
	"syz_proc_sys_generated_1202": alwaysSupported,
	"syz_proc_sys_generated_1203": alwaysSupported,
	"syz_proc_sys_generated_1204": alwaysSupported,
	"syz_proc_sys_generated_1205": alwaysSupported,
	"syz_proc_sys_generated_1206": alwaysSupported,
	"syz_proc_sys_generated_1207": alwaysSupported,
	"syz_proc_sys_generated_1208": alwaysSupported,
	"syz_proc_sys_generated_1209": alwaysSupported,
	"syz_proc_sys_generated_1210": alwaysSupported,
	"syz_proc_sys_generated_1211": alwaysSupported,
	"syz_proc_sys_generated_1212": alwaysSupported,
	"syz_proc_sys_generated_1213": alwaysSupported,
	"syz_proc_sys_generated_1214": alwaysSupported,
	"syz_proc_sys_generated_1215": alwaysSupported,
	"syz_proc_sys_generated_1216": alwaysSupported,
	"syz_proc_sys_generated_1217": alwaysSupported,
	"syz_proc_sys_generated_1218": alwaysSupported,
	"syz_proc_sys_generated_1219": alwaysSupported,
	"syz_proc_sys_generated_1220": alwaysSupported,
	"syz_proc_sys_generated_1221": alwaysSupported,
	"syz_proc_sys_generated_1222": alwaysSupported,
	"syz_proc_sys_generated_1223": alwaysSupported,
	"syz_proc_sys_generated_1224": alwaysSupported,
	"syz_proc_sys_generated_1225": alwaysSupported,
	"syz_proc_sys_generated_1226": alwaysSupported,
	"syz_proc_sys_generated_1227": alwaysSupported,
	"syz_proc_sys_generated_1228": alwaysSupported,
	"syz_proc_sys_generated_1229": alwaysSupported,
	"syz_proc_sys_generated_1230": alwaysSupported,
	"syz_proc_sys_generated_1231": alwaysSupported,
	"syz_proc_sys_generated_1232": alwaysSupported,
	"syz_proc_sys_generated_1233": alwaysSupported,
	"syz_proc_sys_generated_1234": alwaysSupported,
	"syz_proc_sys_generated_1235": alwaysSupported,
	"syz_proc_sys_generated_1236": alwaysSupported,
	"syz_proc_sys_generated_1237": alwaysSupported,
	"syz_proc_sys_generated_1238": alwaysSupported,
	"syz_proc_sys_generated_1239": alwaysSupported,
	"syz_proc_sys_generated_1240": alwaysSupported,
	"syz_proc_sys_generated_1241": alwaysSupported,
	"syz_proc_sys_generated_1242": alwaysSupported,
	"syz_proc_sys_generated_1243": alwaysSupported,
	"syz_proc_sys_generated_1244": alwaysSupported,
	"syz_proc_sys_generated_1245": alwaysSupported,
	"syz_proc_sys_generated_1246": alwaysSupported,
	"syz_proc_sys_generated_1247": alwaysSupported,
	"syz_proc_sys_generated_1248": alwaysSupported,
	"syz_proc_sys_generated_1249": alwaysSupported,
	"syz_proc_sys_generated_1250": alwaysSupported,
	"syz_proc_sys_generated_1251": alwaysSupported,
	"syz_proc_sys_generated_1252": alwaysSupported,
	"syz_proc_sys_generated_1253": alwaysSupported,
	"syz_proc_sys_generated_1254": alwaysSupported,
	"syz_proc_sys_generated_1255": alwaysSupported,
	"syz_proc_sys_generated_1256": alwaysSupported,
	"syz_proc_sys_generated_1257": alwaysSupported,
	"syz_proc_sys_generated_1258": alwaysSupported,
	"syz_proc_sys_generated_1259": alwaysSupported,
	"syz_proc_sys_generated_1260": alwaysSupported,
	"syz_proc_sys_generated_1261": alwaysSupported,
	"syz_proc_sys_generated_1262": alwaysSupported,
	"syz_proc_sys_generated_1263": alwaysSupported,
	"syz_proc_sys_generated_1264": alwaysSupported,
	"syz_proc_sys_generated_1265": alwaysSupported,
	"syz_proc_sys_generated_1266": alwaysSupported,
	"syz_proc_sys_generated_1267": alwaysSupported,
	"syz_proc_sys_generated_1268": alwaysSupported,
	"syz_proc_sys_generated_1269": alwaysSupported,
	"syz_proc_sys_generated_1270": alwaysSupported,
	"syz_proc_sys_generated_1271": alwaysSupported,
	"syz_proc_sys_generated_1272": alwaysSupported,
	"syz_proc_sys_generated_1273": alwaysSupported,
	"syz_proc_sys_generated_1274": alwaysSupported,
	"syz_proc_sys_blob_0":         alwaysSupported,
	"syz_proc_sys_blob_1":         alwaysSupported,
	"syz_proc_sys_blob_2":         alwaysSupported,
	"syz_proc_sys_blob_3":         alwaysSupported,
	"syz_proc_sys_blob_4":         alwaysSupported,
	"syz_proc_sys_blob_5":         alwaysSupported,
	"syz_proc_sys_blob_6":         alwaysSupported,
	"syz_proc_sys_blob_7":         alwaysSupported,
	"syz_proc_sys_blob_8":         alwaysSupported,
	"syz_proc_sys_blob_9":         alwaysSupported,
	"syz_proc_sys_blob_10":        alwaysSupported,
	"syz_proc_sys_blob_11":        alwaysSupported,
	"syz_proc_sys_blob_12":        alwaysSupported,
	"syz_proc_sys_blob_13":        alwaysSupported,
	"syz_proc_sys_blob_14":        alwaysSupported,
	"syz_proc_sys_blob_15":        alwaysSupported,
	"syz_proc_sys_blob_16":        alwaysSupported,
	"syz_proc_sys_blob_17":        alwaysSupported,
	"syz_proc_sys_blob_18":        alwaysSupported,
	"syz_proc_sys_blob_19":        alwaysSupported,
	"syz_proc_sys_blob_20":        alwaysSupported,
	"syz_proc_sys_blob_21":        alwaysSupported,
	"syz_proc_sys_blob_22":        alwaysSupported,
	"syz_proc_sys_blob_23":        alwaysSupported,
	"syz_proc_sys_blob_24":        alwaysSupported,
	"syz_proc_sys_blob_25":        alwaysSupported,
	"syz_proc_sys_blob_26":        alwaysSupported,
	"syz_proc_sys_blob_27":        alwaysSupported,
	"syz_proc_sys_blob_28":        alwaysSupported,
	"syz_proc_sys_blob_29":        alwaysSupported,
	"syz_proc_sys_blob_30":        alwaysSupported,
	"syz_proc_sys_blob_31":        alwaysSupported,
	"syz_proc_sys_blob_32":        alwaysSupported,
	"syz_proc_sys_blob_33":        alwaysSupported,
	"syz_proc_sys_blob_34":        alwaysSupported,
	"syz_proc_sys_blob_35":        alwaysSupported,
	"syz_proc_sys_blob_36":        alwaysSupported,
	"syz_proc_sys_blob_37":        alwaysSupported,
	"syz_proc_sys_blob_38":        alwaysSupported,
	"syz_proc_sys_blob_39":        alwaysSupported,
	"syz_proc_sys_blob_40":        alwaysSupported,
	"syz_proc_sys_blob_41":        alwaysSupported,
	"syz_proc_sys_blob_42":        alwaysSupported,
	"syz_proc_sys_blob_43":        alwaysSupported,
	"syz_proc_sys_blob_44":        alwaysSupported,
	"syz_proc_sys_blob_45":        alwaysSupported,
	"syz_proc_sys_blob_46":        alwaysSupported,
	"syz_proc_sys_blob_47":        alwaysSupported,
	"syz_proc_sys_blob_48":        alwaysSupported,
	"syz_proc_sys_blob_49":        alwaysSupported,
	"syz_proc_sys_blob_50":        alwaysSupported,
	"syz_proc_sys_blob_51":        alwaysSupported,
	"syz_proc_sys_blob_52":        alwaysSupported,
	"syz_proc_sys_blob_53":        alwaysSupported,
	"syz_proc_sys_blob_54":        alwaysSupported,
	"syz_proc_sys_blob_55":        alwaysSupported,
	"syz_proc_sys_blob_56":        alwaysSupported,
	"syz_proc_sys_blob_57":        alwaysSupported,
	"syz_proc_sys_blob_58":        alwaysSupported,
	"syz_proc_sys_blob_59":        alwaysSupported,
	"syz_proc_sys_blob_60":        alwaysSupported,
	"syz_proc_sys_blob_61":        alwaysSupported,
	"syz_proc_sys_blob_62":        alwaysSupported,
	"syz_proc_sys_blob_63":        alwaysSupported,
	"syz_proc_sys_blob_64":        alwaysSupported,
	"syz_proc_sys_blob_65":        alwaysSupported,
	"syz_proc_sys_blob_66":        alwaysSupported,
	"syz_proc_sys_blob_67":        alwaysSupported,
	"syz_proc_sys_blob_68":        alwaysSupported,
	"syz_proc_sys_blob_69":        alwaysSupported,
	"syz_proc_sys_blob_70":        alwaysSupported,
	"syz_proc_sys_blob_71":        alwaysSupported,
	"syz_proc_sys_blob_72":        alwaysSupported,
	"syz_proc_sys_blob_73":        alwaysSupported,
	"syz_proc_sys_blob_74":        alwaysSupported,
	"syz_proc_sys_blob_75":        alwaysSupported,
	"syz_proc_sys_blob_76":        alwaysSupported,
	"syz_proc_sys_blob_77":        alwaysSupported,
	"syz_proc_sys_blob_78":        alwaysSupported,
	"syz_proc_sys_blob_79":        alwaysSupported,
	"syz_proc_sys_blob_80":        alwaysSupported,
	"syz_proc_sys_blob_81":        alwaysSupported,
	"syz_proc_sys_blob_82":        alwaysSupported,
	"syz_proc_sys_blob_83":        alwaysSupported,
	"syz_proc_sys_blob_84":        alwaysSupported,
	"syz_proc_sys_blob_85":        alwaysSupported,
	"syz_proc_sys_blob_86":        alwaysSupported,
	"syz_proc_sys_blob_87":        alwaysSupported,
	"syz_proc_sys_blob_88":        alwaysSupported,
	"syz_proc_sys_blob_89":        alwaysSupported,
	"syz_proc_sys_blob_90":        alwaysSupported,
	"syz_proc_sys_blob_91":        alwaysSupported,
	"syz_proc_sys_blob_92":        alwaysSupported,
	"syz_proc_sys_blob_93":        alwaysSupported,
	"syz_proc_sys_blob_94":        alwaysSupported,
	"syz_proc_sys_blob_95":        alwaysSupported,
	"syz_proc_sys_blob_96":        alwaysSupported,
	"syz_proc_sys_blob_97":        alwaysSupported,
	"syz_proc_sys_blob_98":        alwaysSupported,
	"syz_proc_sys_blob_99":        alwaysSupported,
	"syz_proc_sys_blob_100":       alwaysSupported,
	"syz_proc_sys_blob_101":       alwaysSupported,
	"syz_proc_sys_blob_102":       alwaysSupported,
	"syz_proc_sys_blob_103":       alwaysSupported,
	"syz_proc_sys_blob_104":       alwaysSupported,
	"syz_proc_sys_blob_105":       alwaysSupported,
	"syz_proc_sys_blob_106":       alwaysSupported,
	"syz_proc_sys_blob_107":       alwaysSupported,
	"syz_proc_sys_blob_108":       alwaysSupported,
	"syz_proc_sys_blob_109":       alwaysSupported,
	"syz_proc_sys_blob_110":       alwaysSupported,
	"syz_proc_sys_blob_111":       alwaysSupported,
	"syz_proc_sys_blob_112":       alwaysSupported,
	"syz_proc_sys_blob_113":       alwaysSupported,
	"syz_proc_sys_blob_114":       alwaysSupported,
	"syz_proc_sys_blob_115":       alwaysSupported,
	"syz_proc_sys_blob_116":       alwaysSupported,
	"syz_proc_sys_blob_117":       alwaysSupported,
	"syz_proc_sys_blob_118":       alwaysSupported,
	"syz_proc_sys_blob_119":       alwaysSupported,
	"syz_proc_sys_blob_120":       alwaysSupported,
	"syz_proc_sys_blob_121":       alwaysSupported,
	"syz_proc_sys_blob_122":       alwaysSupported,
	"syz_proc_sys_blob_123":       alwaysSupported,
	"syz_proc_sys_blob_124":       alwaysSupported,
	"syz_proc_sys_blob_125":       alwaysSupported,
	"syz_proc_sys_blob_126":       alwaysSupported,
	"syz_proc_sys_blob_127":       alwaysSupported,
	"syz_proc_sys_blob_128":       alwaysSupported,
	"syz_proc_sys_blob_129":       alwaysSupported,
	"syz_proc_sys_blob_130":       alwaysSupported,
	"syz_proc_sys_blob_131":       alwaysSupported,
	"syz_proc_sys_blob_132":       alwaysSupported,
	"syz_proc_sys_blob_133":       alwaysSupported,
	"syz_proc_sys_blob_134":       alwaysSupported,
	"syz_proc_sys_blob_135":       alwaysSupported,
	"syz_proc_sys_blob_136":       alwaysSupported,
	"syz_proc_sys_blob_137":       alwaysSupported,
	"syz_proc_sys_blob_138":       alwaysSupported,
	"syz_proc_sys_blob_139":       alwaysSupported,
	"syz_proc_sys_blob_140":       alwaysSupported,
	"syz_proc_sys_blob_141":       alwaysSupported,
	"syz_proc_sys_blob_142":       alwaysSupported,
	"syz_proc_sys_blob_143":       alwaysSupported,
	"syz_proc_sys_blob_144":       alwaysSupported,
	"syz_proc_sys_blob_145":       alwaysSupported,
	"syz_proc_sys_blob_146":       alwaysSupported,
	"syz_proc_sys_blob_147":       alwaysSupported,
	"syz_proc_sys_blob_148":       alwaysSupported,
	"syz_proc_sys_blob_149":       alwaysSupported,
	"syz_proc_sys_blob_150":       alwaysSupported,
	"syz_proc_sys_blob_151":       alwaysSupported,
	"syz_proc_sys_blob_152":       alwaysSupported,
	"syz_proc_sys_blob_153":       alwaysSupported,
	"syz_proc_sys_blob_154":       alwaysSupported,
	"syz_proc_sys_blob_155":       alwaysSupported,
	"syz_proc_sys_blob_156":       alwaysSupported,
	"syz_proc_sys_blob_157":       alwaysSupported,
	"syz_proc_sys_blob_158":       alwaysSupported,
	"syz_proc_sys_blob_159":       alwaysSupported,
	"syz_proc_sys_blob_160":       alwaysSupported,
	"syz_proc_sys_blob_161":       alwaysSupported,
	"syz_proc_sys_blob_162":       alwaysSupported,
	"syz_proc_sys_blob_163":       alwaysSupported,
	"syz_proc_sys_blob_164":       alwaysSupported,
	"syz_proc_sys_blob_165":       alwaysSupported,
	"syz_proc_sys_blob_166":       alwaysSupported,
	"syz_proc_sys_blob_167":       alwaysSupported,
	"syz_proc_sys_blob_168":       alwaysSupported,
	"syz_proc_sys_blob_169":       alwaysSupported,
	"syz_proc_sys_blob_170":       alwaysSupported,
	"syz_proc_sys_blob_171":       alwaysSupported,
	"syz_proc_sys_blob_172":       alwaysSupported,
	"syz_proc_sys_blob_173":       alwaysSupported,
	"syz_proc_sys_blob_174":       alwaysSupported,
	"syz_proc_sys_blob_175":       alwaysSupported,
	"syz_proc_sys_blob_176":       alwaysSupported,
	"syz_proc_sys_blob_177":       alwaysSupported,
	"syz_proc_sys_blob_178":       alwaysSupported,
	"syz_proc_sys_blob_179":       alwaysSupported,
	"syz_proc_sys_blob_180":       alwaysSupported,
	"syz_proc_sys_blob_181":       alwaysSupported,
	"syz_proc_sys_blob_182":       alwaysSupported,
	"syz_proc_sys_blob_183":       alwaysSupported,
	"syz_proc_sys_blob_184":       alwaysSupported,
	"syz_proc_sys_blob_185":       alwaysSupported,
	"syz_proc_sys_blob_186":       alwaysSupported,
	"syz_proc_sys_blob_187":       alwaysSupported,
	"syz_proc_sys_blob_188":       alwaysSupported,
	"syz_proc_sys_blob_189":       alwaysSupported,
	"syz_proc_sys_blob_190":       alwaysSupported,
	"syz_proc_sys_blob_191":       alwaysSupported,
	"syz_proc_sys_blob_192":       alwaysSupported,
	"syz_proc_sys_blob_193":       alwaysSupported,
	"syz_proc_sys_blob_194":       alwaysSupported,
	"syz_proc_sys_blob_195":       alwaysSupported,
	"syz_proc_sys_blob_196":       alwaysSupported,
	"syz_proc_sys_blob_197":       alwaysSupported,
	"syz_proc_sys_blob_198":       alwaysSupported,
	"syz_proc_sys_blob_199":       alwaysSupported,
	"syz_proc_sys_blob_200":       alwaysSupported,
	"syz_proc_sys_blob_201":       alwaysSupported,
	"syz_proc_sys_blob_202":       alwaysSupported,
	"syz_proc_sys_blob_203":       alwaysSupported,
	"syz_proc_sys_blob_204":       alwaysSupported,
	"syz_proc_sys_blob_205":       alwaysSupported,
	"syz_proc_sys_blob_206":       alwaysSupported,
	"syz_proc_sys_blob_207":       alwaysSupported,
	"syz_proc_sys_blob_208":       alwaysSupported,
	"syz_proc_sys_blob_209":       alwaysSupported,
	"syz_proc_sys_blob_210":       alwaysSupported,
	"syz_proc_sys_blob_211":       alwaysSupported,
	"syz_proc_sys_blob_212":       alwaysSupported,
	"syz_proc_sys_blob_213":       alwaysSupported,
	"syz_proc_sys_blob_214":       alwaysSupported,
	"syz_proc_sys_blob_215":       alwaysSupported,
	"syz_proc_sys_blob_216":       alwaysSupported,
	"syz_proc_sys_blob_217":       alwaysSupported,
	"syz_proc_sys_blob_218":       alwaysSupported,
	"syz_proc_sys_blob_219":       alwaysSupported,
	"syz_proc_sys_blob_220":       alwaysSupported,
	"syz_proc_sys_blob_221":       alwaysSupported,
	"syz_proc_sys_blob_222":       alwaysSupported,
	"syz_proc_sys_blob_223":       alwaysSupported,
	"syz_proc_sys_blob_224":       alwaysSupported,
}

func linuxSyzOpenDevSupported(ctx *checkContext, call *prog.Syscall) string {
	if _, ok := call.Args[0].Type.(*prog.ConstType); ok || call.Attrs.Automatic {
		// This is for syz_open_dev$char/block.
		// second operand for when we have an automatically generated description
		return ""
	}
	fname, ok := extractStringConst(call.Args[0].Type, call.Attrs.Automatic)
	if !ok {
		panic("first open arg is not a pointer to string const")
	}
	hashCount := strings.Count(fname, "#")
	if hashCount == 0 {
		panic(fmt.Sprintf("%v does not contain # in the file name", call.Name))
	}
	if hashCount > 2 {
		// If this fails, the logic below needs an adjustment.
		panic(fmt.Sprintf("%v contains too many #", call.Name))
	}
	var ids []int
	if _, ok := call.Args[1].Type.(*prog.ProcType); ok {
		ids = []int{0}
	} else {
		for i := 0; i < 5; i++ {
			for j := 0; j < 5; j++ {
				if j == 0 || hashCount > 1 {
					ids = append(ids, i+j*10)
				}
			}
		}
	}
	modes := ctx.allOpenModes()
	var calls []string
	for _, id := range ids {
		for _, mode := range modes {
			call := fmt.Sprintf("%s(&AUTO='%v', 0x%x, 0x%x)", call.Name, fname, id, mode)
			calls = append(calls, call)
		}
	}
	reason := ctx.anyCallSucceeds(calls, fmt.Sprintf("failed to open %v", fname))
	if reason != "" {
		// These entries might not be available at boot time,
		// but will be created by connected USB devices.
		for _, prefix := range []string{"/dev/hidraw", "/dev/usb/hiddev", "/dev/input/"} {
			if strings.HasPrefix(fname, prefix) {
				if ctx.rootCanOpen("/dev/raw-gadget") == "" {
					reason = ""
				}
			}
		}
	}
	return reason
}

func linuxNetInjectionSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.rootCanOpen("/dev/net/tun")
}

func linuxSyzOpenProcfsSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.canOpen("/proc/cmdline")
}

func linuxCheckUSBEmulation(ctx *checkContext, call *prog.Syscall) string {
	return ctx.rootCanOpen("/dev/raw-gadget")
}

const unsupportedArch = "unsupported arch"

func linuxSyzKvmSetupCPUSupported(ctx *checkContext, call *prog.Syscall) string {
	switch call.Name {
	case "syz_kvm_setup_cpu$x86":
		if ctx.target.Arch == targets.AMD64 || ctx.target.Arch == targets.I386 {
			return ""
		}
	case "syz_kvm_setup_cpu$arm64":
		if ctx.target.Arch == targets.ARM64 {
			return ""
		}
	case "syz_kvm_setup_cpu$ppc64":
		if ctx.target.Arch == targets.PPC64LE {
			return ""
		}
	}
	return unsupportedArch
}

func linuxSyzSupportedOnArm64(ctx *checkContext, call *prog.Syscall) string {
	if ctx.target.Arch == targets.ARM64 {
		return ""
	}
	return unsupportedArch
}

func linuxSupportedMount(ctx *checkContext, call *prog.Syscall) string {
	return linuxSupportedFilesystem(ctx, call, 2)
}

func linuxSyzMountImageSupported(ctx *checkContext, call *prog.Syscall) string {
	return linuxSupportedFilesystem(ctx, call, 0)
}

func linuxSupportedFilesystem(ctx *checkContext, call *prog.Syscall, fsarg int) string {
	if call.Attrs.Automatic {
		return ""
	}
	fstype, ok := extractStringConst(call.Args[fsarg].Type, call.Attrs.Automatic)
	if !ok {
		panic(fmt.Sprintf("%v: filesystem is not string const", call.Name))
	}
	switch fstype {
	case "fuse", "fuseblk":
		if reason := ctx.canOpen("/dev/fuse"); reason != "" {
			return reason
		}
		if reason := ctx.onlySandboxNoneOrNamespace(); reason != "" {
			return reason
		}
	default:
		if reason := ctx.onlySandboxNone(); reason != "" {
			return reason
		}
	}
	filesystems, err := ctx.readFile("/proc/filesystems")
	if err != nil {
		return err.Error()
	}
	if !bytes.Contains(filesystems, []byte("\t"+fstype+"\n")) {
		return fmt.Sprintf("/proc/filesystems does not contain %v", fstype)
	}
	return ""
}

func linuxSyzReadPartTableSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.onlySandboxNone()
}

func linuxSupportedSocket(ctx *checkContext, call *prog.Syscall) string {
	if call.Name == "socket" || call.Name == "socketpair" || call.Attrs.Automatic {
		return "" // generic versions are always supported
	}
	af := uint64(0)
	if arg, ok := call.Args[0].Type.(*prog.ConstType); ok {
		af = arg.Val
	} else {
		panic(fmt.Sprintf("socket family is not const in %v", call.Name))
	}
	typ, hasType := uint64(0), false
	if arg, ok := call.Args[1].Type.(*prog.ConstType); ok {
		typ, hasType = arg.Val, true
	} else if arg, ok := call.Args[1].Type.(*prog.FlagsType); ok {
		typ, hasType = arg.Vals[0], true
	}
	proto, hasProto := uint64(0), false
	if arg, ok := call.Args[2].Type.(*prog.ConstType); ok {
		proto, hasProto = arg.Val, true
	}
	syscallName := call.Name
	if call.CallName == "socketpair" {
		syscallName = "socket"
	}
	callStr := fmt.Sprintf("%s(0x%x, 0x%x, 0x%x)", syscallName, af, typ, proto)
	errno := ctx.execCall(callStr)
	if errno == syscall.ENOSYS || errno == syscall.EAFNOSUPPORT || hasProto && hasType && errno != 0 {
		return fmt.Sprintf("%v failed: %v", callStr, errno)
	}
	return ""
}

func linuxSyzGenetlinkGetFamilyIDSupported(ctx *checkContext, call *prog.Syscall) string {
	// TODO: try to obtain actual family ID here. It will disable whole sets of sendmsg syscalls.
	return ctx.callSucceeds(fmt.Sprintf("socket(0x%x, 0x%x, 0x%x)",
		ctx.val("AF_NETLINK"), ctx.val("SOCK_RAW"), ctx.val("NETLINK_GENERIC")))
}

func linuxPkeysSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.callSucceeds("pkey_alloc(0x0, 0x0)")
}

func linuxSyzSocketConnectNvmeTCPSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.onlySandboxNone()
}

func linuxVhciInjectionSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.rootCanOpen("/dev/vhci")
}

func linuxSyzInitNetSocketSupported(ctx *checkContext, call *prog.Syscall) string {
	if reason := ctx.onlySandboxNone(); reason != "" {
		return reason
	}
	return linuxSupportedSocket(ctx, call)
}

func linuxBtfVmlinuxSupported(ctx *checkContext, call *prog.Syscall) string {
	if reason := ctx.onlySandboxNone(); reason != "" {
		return reason
	}
	return ctx.canOpen("/sys/kernel/btf/vmlinux")
}

func linuxSyzUsbIPSupported(ctx *checkContext, call *prog.Syscall) string {
	return ctx.canWrite("/sys/devices/platform/vhci_hcd.0/attach")
}

func linuxWifiEmulationSupported(ctx *checkContext, call *prog.Syscall) string {
	if reason := ctx.rootCanOpen("/sys/class/mac80211_hwsim/"); reason != "" {
		return reason
	}
	// We use HWSIM_ATTR_PERM_ADDR which was added in 4.17.
	return linuxRequireKernel(ctx, 4, 17)
}

func linuxRequireKernel(ctx *checkContext, major, minor int) string {
	data, err := ctx.readFile("/proc/version")
	if err != nil {
		return err.Error()
	}
	if ok, bad := matchKernelVersion(string(data), major, minor); bad {
		return fmt.Sprintf("failed to parse kernel version: %s", data)
	} else if !ok {
		return fmt.Sprintf("kernel %v.%v required, have %s", major, minor, data)
	}
	return ""
}

var kernelVersionRe = regexp.MustCompile(` ([0-9]+)\.([0-9]+)\.`)

func matchKernelVersion(ver string, x, y int) (bool, bool) {
	match := kernelVersionRe.FindStringSubmatch(ver)
	if match == nil {
		return false, true
	}
	major, err := strconv.Atoi(match[1])
	if err != nil {
		return false, true
	}
	if major <= 0 || major > 999 {
		return false, true
	}
	minor, err := strconv.Atoi(match[2])
	if err != nil {
		return false, true
	}
	if minor <= 0 || minor > 999 {
		return false, true
	}
	return major*1000+minor >= x*1000+y, false
}
