// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/swap.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/capability.h>
#include <linux/falloc.h>

static __thread int clone_ongoing;
static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  if (__atomic_load_n(&clone_ongoing, __ATOMIC_RELAXED) != 0) {
    exit(sig);
  }
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

static int runcmdline(char* cmdline)
{
  int ret = system(cmdline);
  if (ret) {
  }
  return ret;
}

#define MAX_FDS 30

static void setup_gadgetfs();
static void setup_binderfs();
static void setup_fusectl();
static void sandbox_common_mount_tmpfs(void)
{
  write_file("/proc/sys/fs/mount-max", "100000");
  if (mkdir("./syz-tmp", 0777))
    exit(1);
  if (mount("", "./syz-tmp", "tmpfs", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot", 0777))
    exit(1);
  if (mkdir("./syz-tmp/newroot/dev", 0700))
    exit(1);
  unsigned bind_mount_flags = MS_BIND | MS_REC | MS_PRIVATE;
  if (mount("/dev", "./syz-tmp/newroot/dev", NULL, bind_mount_flags, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/proc", 0700))
    exit(1);
  if (mount("syz-proc", "./syz-tmp/newroot/proc", "proc", 0, NULL))
    exit(1);
  if (mkdir("./syz-tmp/newroot/selinux", 0700))
    exit(1);
  const char* selinux_path = "./syz-tmp/newroot/selinux";
  if (mount("/selinux", selinux_path, NULL, bind_mount_flags, NULL)) {
    if (errno != ENOENT)
      exit(1);
    if (mount("/sys/fs/selinux", selinux_path, NULL, bind_mount_flags, NULL) &&
        errno != ENOENT)
      exit(1);
  }
  if (mkdir("./syz-tmp/newroot/sys", 0700))
    exit(1);
  if (mount("/sys", "./syz-tmp/newroot/sys", 0, bind_mount_flags, NULL))
    exit(1);
  if (mount("/sys/kernel/debug", "./syz-tmp/newroot/sys/kernel/debug", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/sys/fs/smackfs", "./syz-tmp/newroot/sys/fs/smackfs", NULL,
            bind_mount_flags, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mount("/proc/sys/fs/binfmt_misc",
            "./syz-tmp/newroot/proc/sys/fs/binfmt_misc", NULL, bind_mount_flags,
            NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/newroot/syz-inputs", 0700))
    exit(1);
  if (mount("/syz-inputs", "./syz-tmp/newroot/syz-inputs", NULL,
            bind_mount_flags | MS_RDONLY, NULL) &&
      errno != ENOENT)
    exit(1);
  if (mkdir("./syz-tmp/pivot", 0777))
    exit(1);
  if (syscall(SYS_pivot_root, "./syz-tmp", "./syz-tmp/pivot")) {
    if (chdir("./syz-tmp"))
      exit(1);
  } else {
    if (chdir("/"))
      exit(1);
    if (umount2("./pivot", MNT_DETACH))
      exit(1);
  }
  if (chroot("./newroot"))
    exit(1);
  if (chdir("/"))
    exit(1);
  setup_gadgetfs();
  setup_binderfs();
  setup_fusectl();
}

static void setup_gadgetfs()
{
  if (mkdir("/dev/gadgetfs", 0777)) {
  }
  if (mount("gadgetfs", "/dev/gadgetfs", "gadgetfs", 0, NULL)) {
  }
}

static void setup_fusectl()
{
  if (mount(0, "/sys/fs/fuse/connections", "fusectl", 0, 0)) {
  }
}

static void setup_binderfs()
{
  if (mkdir("/dev/binderfs", 0777)) {
  }
  if (mount("binder", "/dev/binderfs", "binder", 0, NULL)) {
  }
  if (symlink("/dev/binderfs", "./binderfs")) {
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  if (getppid() == 1)
    exit(1);
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = (200 << 20);
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 32 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
  typedef struct {
    const char* name;
    const char* value;
  } sysctl_t;
  static const sysctl_t sysctls[] = {
      {"/proc/sys/kernel/shmmax", "16777216"},
      {"/proc/sys/kernel/shmall", "536870912"},
      {"/proc/sys/kernel/shmmni", "1024"},
      {"/proc/sys/kernel/msgmax", "8192"},
      {"/proc/sys/kernel/msgmni", "1024"},
      {"/proc/sys/kernel/msgmnb", "1024"},
      {"/proc/sys/kernel/sem", "1024 1048576 500 1024"},
  };
  unsigned i;
  for (i = 0; i < sizeof(sysctls) / sizeof(sysctls[0]); i++)
    write_file(sysctls[i].name, sysctls[i].value);
}

static int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static void drop_caps(void)
{
  struct __user_cap_header_struct cap_hdr = {};
  struct __user_cap_data_struct cap_data[2] = {};
  cap_hdr.version = _LINUX_CAPABILITY_VERSION_3;
  cap_hdr.pid = getpid();
  if (syscall(SYS_capget, &cap_hdr, &cap_data))
    exit(1);
  const int drop = (1 << CAP_SYS_PTRACE) | (1 << CAP_SYS_NICE);
  cap_data[0].effective &= ~drop;
  cap_data[0].permitted &= ~drop;
  cap_data[0].inheritable &= ~drop;
  if (syscall(SYS_capset, &cap_hdr, &cap_data))
    exit(1);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  sandbox_common();
  drop_caps();
  if (unshare(CLONE_NEWNET)) {
  }
  write_file("/proc/sys/net/ipv4/ping_group_range", "0 65535");
  sandbox_common_mount_tmpfs();
  loop();
  exit(1);
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void close_fds()
{
  for (int fd = 3; fd < MAX_FDS; fd++)
    close(fd);
}

#define SWAP_FILE "./swap-file"
#define SWAP_FILE_SIZE (128 * 1000 * 1000)

static const char* setup_swap()
{
  swapoff(SWAP_FILE);
  unlink(SWAP_FILE);
  int fd = open(SWAP_FILE, O_CREAT | O_WRONLY | O_CLOEXEC, 0600);
  if (fd == -1)
    return "swap file open failed";
  fallocate(fd, FALLOC_FL_ZERO_RANGE, 0, SWAP_FILE_SIZE);
  close(fd);
  char cmdline[64];
  sprintf(cmdline, "mkswap %s", SWAP_FILE);
  if (runcmdline(cmdline))
    return "mkswap failed";
  if (swapon(SWAP_FILE, SWAP_FLAG_PREFER) == 1)
    return "swapon failed";
  return NULL;
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      close_fds();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

uint64_t r[1] = {0xffffffffffffffff};

void execute_one(void)
{
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  perf_event_open arguments: [
  //    attr: ptr[in, perf_event_attr] {
  //      perf_event_attr {
  //        type: perf_event_type = 0x2 (4 bytes)
  //        size: len = 0x80 (4 bytes)
  //        config0: int8 = 0x80 (1 bytes)
  //        config1: int8 = 0x0 (1 bytes)
  //        config2: int8 = 0x0 (1 bytes)
  //        config3: int8 = 0x0 (1 bytes)
  //        config4: const = 0x0 (4 bytes)
  //        sample_freq: int64 = 0x1 (8 bytes)
  //        sample_type: perf_sample_type = 0x0 (8 bytes)
  //        read_format: perf_read_format = 0x0 (8 bytes)
  //        disabled: int64 = 0x0 (0 bytes)
  //        inherit: int64 = 0x0 (0 bytes)
  //        pinned: int64 = 0x0 (0 bytes)
  //        exclusive: int64 = 0x0 (0 bytes)
  //        exclude_user: int64 = 0x0 (0 bytes)
  //        exclude_kernel: int64 = 0x0 (0 bytes)
  //        exclude_hv: int64 = 0x0 (0 bytes)
  //        exclude_idle: int64 = 0x0 (0 bytes)
  //        mmap: int64 = 0x0 (0 bytes)
  //        comm: int64 = 0x0 (0 bytes)
  //        freq: int64 = 0x0 (0 bytes)
  //        inherit_stat: int64 = 0x0 (0 bytes)
  //        enable_on_exec: int64 = 0x0 (0 bytes)
  //        task: int64 = 0x0 (0 bytes)
  //        watermark: int64 = 0x0 (0 bytes)
  //        precise_ip: int64 = 0x0 (0 bytes)
  //        mmap_data: int64 = 0x0 (0 bytes)
  //        sample_id_all: int64 = 0x0 (0 bytes)
  //        exclude_host: int64 = 0x0 (0 bytes)
  //        exclude_guest: int64 = 0x0 (0 bytes)
  //        exclude_callchain_kernel: int64 = 0x0 (0 bytes)
  //        exclude_callchain_user: int64 = 0x0 (0 bytes)
  //        mmap2: int64 = 0x0 (0 bytes)
  //        comm_exec: int64 = 0x0 (0 bytes)
  //        use_clockid: int64 = 0x0 (0 bytes)
  //        context_switch: int64 = 0x0 (0 bytes)
  //        write_backward: int64 = 0x0 (0 bytes)
  //        namespaces: int64 = 0x0 (0 bytes)
  //        ksymbol: int64 = 0x0 (0 bytes)
  //        bpf_event: int64 = 0x0 (0 bytes)
  //        aux_output: int64 = 0x0 (0 bytes)
  //        cgroup: int64 = 0x0 (0 bytes)
  //        text_poke: int64 = 0x0 (0 bytes)
  //        build_id: int64 = 0x0 (0 bytes)
  //        inherit_thread: int64 = 0x0 (0 bytes)
  //        remove_on_exec: int64 = 0x0 (0 bytes)
  //        sigtrap: int64 = 0x0 (0 bytes)
  //        __reserved_1: const = 0x0 (8 bytes)
  //        wakeup_events: int32 = 0x0 (4 bytes)
  //        bp_type: perf_bp_type = 0x0 (4 bytes)
  //        bp_config: union perf_bp_config {
  //          perf_config_ext: perf_config_ext {
  //            config1: int64 = 0xd1 (8 bytes)
  //            config2: int64 = 0x0 (8 bytes)
  //          }
  //        }
  //        branch_sample_type: perf_branch_sample_type = 0x0 (8 bytes)
  //        sample_regs_user: int64 = 0x0 (8 bytes)
  //        sample_stack_user: int32 = 0x0 (4 bytes)
  //        clockid: clock_type = 0x0 (4 bytes)
  //        sample_regs_intr: int64 = 0x0 (8 bytes)
  //        aux_watermark: int32 = 0xb1a (4 bytes)
  //        sample_max_stack: int16 = 0x0 (2 bytes)
  //        __reserved_2: const = 0x0 (2 bytes)
  //        aux_sample_size: int32 = 0x0 (4 bytes)
  //        __reserved_3: const = 0x0 (4 bytes)
  //        sig_data: int64 = 0x0 (8 bytes)
  //      }
  //    }
  //    pid: pid (resource)
  //    cpu: intptr = 0x0 (8 bytes)
  //    group: fd_perf (resource)
  //    flags: perf_flags = 0x0 (8 bytes)
  //  ]
  //  returns fd_perf
  NONFAILING(*(uint32_t*)0x200000000100 = 2);
  NONFAILING(*(uint32_t*)0x200000000104 = 0x80);
  NONFAILING(*(uint8_t*)0x200000000108 = 0x80);
  NONFAILING(*(uint8_t*)0x200000000109 = 0);
  NONFAILING(*(uint8_t*)0x20000000010a = 0);
  NONFAILING(*(uint8_t*)0x20000000010b = 0);
  NONFAILING(*(uint32_t*)0x20000000010c = 0);
  NONFAILING(*(uint64_t*)0x200000000110 = 1);
  NONFAILING(*(uint64_t*)0x200000000118 = 0);
  NONFAILING(*(uint64_t*)0x200000000120 = 0);
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 0, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 1, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 2, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 3, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 4, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 5, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 6, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 7, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 8, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 9, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 10, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 11, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 12, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 13, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 14, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 15, 2));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 17, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 18, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 19, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 20, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 21, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 22, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 23, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 24, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 25, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 26, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 27, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 28, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 29, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 30, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 31, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 32, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 33, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 34, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 35, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 36, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 37, 1));
  NONFAILING(STORE_BY_BITMASK(uint64_t, , 0x200000000128, 0, 38, 26));
  NONFAILING(*(uint32_t*)0x200000000130 = 0);
  NONFAILING(*(uint32_t*)0x200000000134 = 0);
  NONFAILING(*(uint64_t*)0x200000000138 = 0xd1);
  NONFAILING(*(uint64_t*)0x200000000140 = 0);
  NONFAILING(*(uint64_t*)0x200000000148 = 0);
  NONFAILING(*(uint64_t*)0x200000000150 = 0);
  NONFAILING(*(uint32_t*)0x200000000158 = 0);
  NONFAILING(*(uint32_t*)0x20000000015c = 0);
  NONFAILING(*(uint64_t*)0x200000000160 = 0);
  NONFAILING(*(uint32_t*)0x200000000168 = 0xb1a);
  NONFAILING(*(uint16_t*)0x20000000016c = 0);
  NONFAILING(*(uint16_t*)0x20000000016e = 0);
  NONFAILING(*(uint32_t*)0x200000000170 = 0);
  NONFAILING(*(uint32_t*)0x200000000174 = 0);
  NONFAILING(*(uint64_t*)0x200000000178 = 0);
  res = syscall(__NR_perf_event_open, /*attr=*/0x200000000100ul, /*pid=*/0,
                /*cpu=*/0ul, /*group=*/(intptr_t)-1, /*flags=*/0ul);
  if (res != -1)
    r[0] = res;
  //  ioctl$PERF_EVENT_IOC_PERIOD arguments: [
  //    fd: fd_perf (resource)
  //    cmd: const = 0x40082404 (4 bytes)
  //    period: ptr[in, int64] {
  //      int64 = 0x9 (8 bytes)
  //    }
  //  ]
  NONFAILING(*(uint64_t*)0x200000000340 = 9);
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x40082404,
          /*period=*/0x200000000340ul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  if ((reason = setup_swap()))
    printf("the reproducer may not work as expected: swap setup failed: %s\n",
           reason);
  install_segv_handler();
  do_sandbox_none();
  return 0;
}
